### ISSUE TITLE
Проблема с touch.bundles и touch.blocks

### ISSUE THREAD

**Issue by Integer64** [bem-site/bem-forum-content-ru#1073]
Всем привет! Подскажите как правильно переопределять блоки для бандлов. Т.е. у нас есть desktop.blocks/header и touch-phone.blocks/header. Почему блок header определенный в touch-phone.bundles/index/index.bemjson.js подключаются из desktop.blocks, а не touch-phone.blocks?

**Comment by soltx** [comment]
столкнулся с такой же проблемой, может кто скинет пример реализации

например у меня следующая структура:
```
common.blocks
mobile.bloсks
         |__header
                |_header.styl

desktop.bloсks
         |_header
               |_header.styl

desktop.bundles
         |_index
                 |_index.bemjson.js
         |_contacts
                 |_contacts.bemjson.js

mobile.bundles
         |_index
                |_index.bemjson.js
         |_contacts
               |_contacts.bemjson.js
```
собственно стили для header из mobile.blocks применились для desktop.bundles

**Comment by apsavin** [comment]
@Integer64 @soltx а у вас enb или bem-tools?
Скорее всего, enb.
Тогда нужно настроить сборку в `.enb/make.js`. Почитать про настройку enb можно в readme официального репозитория и на bem.info.

**Comment by tadatuta** [comment]
Если разбирать на примере https://github.com/bem/project-stub/, то вот здесь
https://github.com/bem/project-stub/blob/master/.enb/make.js#L37 сейчас матчатся вообще все возможные бандлы, а вот тут подключаются уровни https://github.com/bem/project-stub/blob/master/.enb/make.js#L40
В итоге один и тот же набор уровней будет у любых бандлов.

Чтобы их разделить, нужно отдельно определить набор уровней для каждого варианта бандлов:
```js
config.nodes('desktop.bundles/*', function(nodeConfig) {
    nodeConfig.addTechs([
        [enbBemTechs.levels, { levels: ['desktop.blocks'] }]
    ]);
});

config.nodes('touch.bundles/*', function(nodeConfig) {
    nodeConfig.addTechs([
        [enbBemTechs.levels, { levels: ['touch.blocks'] }]
    ]);
});

config.nodes('*.bundles/*', function(nodeConfig) {
    // здесь все остальные технологии сборки, универсальные для каждого набора бандлов
});
```
