### ISSUE TITLE
Генерация в ENB файлов '.bemhtml.js' без кода BEM-XJST компилятора

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1097]
Нужно получать на выходе файл с шаблонами бандла без обёрточного кода BEM-XJST (`BEM-XJST User-code Start ... BEM-XJST User-code End`).

Пока придумал добавить свою технологию, которая из имеющегося **.bemhtml.js** создавала к.-ндь **.bemhtml.raw.js**, выкусывая всё, кроме шаблонов.

Есть ли более изящный способ?

В опциях к самому **techs/bemhtml** ничего годного не вижу.

**Comment by blond** [comment]
@lilliputten, если я правильно понял задачу, то можно собирать `bemhtml.js` файлы как обычный JavaScript с помощью [enb-js](https://github.com/enb/enb-js).

А зачем, если не секрет, BEMHTML без обёртки?

**Comment by lilliputten** [comment]
@blond

(1) У меня всё уже сильно закручено на enb/borschik и gulp сверху, -- проблемы бывают, но радикально менять пока нет смысле, особенно с учётом объёмов накопленного кода. Т.е., к сожалению, не подходит.

(2) Обёртка мне не нужна -- bem-xjst у меня живёт отдельным модулем и ему в динамике по мере необходимости подсовываются нужные бандлы с шаблонами. На рабочем сервере всё нормально (подготавливается gulp'ом), но хочется динамические компоненты проверять и на enb-шном сервере, -- т.е., нужно допилить сборщик.

Сейчас сделал именно по принципу ещё одной технологии сверху: `techs/bemhtml` создаёт теперь __.bemhtmlx.js__, а из него уже мой `techs/enb-bemhtmlrepack` делает очищенный __.bemhtml__. Изврат, конечно, но куда же без извратов?

**Comment by zxqfox** [comment]
@lilliputten Не очень понятно, почему нельзя просто склеить файлы шаблонов в правильном порядке. Вроде бы enb-js действительно мог бы подойти.

Если хочется борщик, то https://github.com/enb/enb-borschik/blob/master/api.ru.md#js-borschik-include
