### ISSUE TITLE
Удаление блоков (destruct?)

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1103]
Как правильно удалять блоки? Делаю `BEMDOM.destruct(...)`, но остаются подписки на события. В доках/коде пока решения откопать не удаётся

**Comment by tadatuta** [comment]
@lilliputten в текущей версии `bem-core` не все подписки могут быть удалены автоматически. нужен пример кода, чтобы ответить более предметно.
