### ISSUE TITLE
Доступ к "родителю" при доопределении блока через модификатор

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1122]
Доопределяю через модификтор блок `input` для работы с датами (выбор из всплывающего календаря, преобразования js-date/readable string). Испольую `mods : { date : true }` и, соотв.:

```
modules.define('input', [ ... ], function (...) {
    provide(Input.decl({ modName : 'date', modVal : true }, {
        /* мой код модуля */
    } ));
});
```

Могу ли по аналогии с расширением класса использовать методы блока-родителя? Т.е., напр. определить свой метод `setVal()`, который будет передавать преобразованное значение родительскому методу `setVal()`?

Думал достучаться через `this.__base`, но примеров такого подхода не обнаружил.

Это возможно? Как?

**Comment by tadatuta** [comment]
@lilliputten именно через `this.__base()` и можно:

```js
setVal: function(val) {
    var newVal = doSomethingWithVal(val);

    return this.__base(val);
}
```

**Comment by lilliputten** [comment]
Действительно, как-то недосмотрел. :( Проверил, работает. Спасибо!
