### ISSUE TITLE
Правильное наименование папок/файлов для описания сущности элемента блока с модификатором

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1125]
Вопрос про физическое наименование/расположение папок и файлов для подсовывания _enb_.

Для модикатора использую `_modName/blockName_modName.*`, для элемента `__elemName/blockName__elemName.*`.

А для элемента блока с определённым модификатором. Вопреки ожиданиям, `_modName__elemName/...` не работает. Хотя для `_modName1_modName2`, напр., -- запросто.

Есть к.-то паттерн подходящий?

**Comment by tadatuta** [comment]
Если речь о том, что есть некий блок `b1`, у которого есть модификатор `b1_m1` и необходимо создать файл для его элемента `b1__e1`, который бы подключался только тогда, когда у блока есть данный модификатор, то такой штуки нет. Стоит просто положить нужный для элемента код в файл модификатора `b1_m1`.

А если речь о том, что нужно отдельно держать код модификатора элемента, то паттерн такой: `block-name/__elem-name/_elem-mod-name/block-name__elem-name_elem-mod-name.js`.

Собственно все поддерживаемые варианты описаны тут: https://ru.bem.info/methodology/filesystem/#nested (используемая по умолчанию в ENB схема называется `nested`).
