### ISSUE TITLE
Применение маски '*' в bemhtml предикате elem: elem('*')

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1147]
Не понял, как в bemhtml работает маска `*` для элементов (в соотв. с [синтаксисом шаблонов](https://ru.bem.info/platform/bem-xjst/templates-syntax/#elem): "_...В качестве name можно использовать '*'..._"). Но пробую:

```
block('block_name').elem('*')( /* ... */ )
```

-- и получается, что находятся элементы, не только принадлежащие блоку `block_name`. Если правильно понял, находятся вообще ВСЕ элементы.

Что-то не так понял? Что-то не так делаю?

**Comment by vithar** [comment]
@miripiruni это баг

**Comment by miripiruni** [comment]
Да, это баг. Еще есть такое: https://github.com/bem/bem-xjst/issues/256
