### ISSUE TITLE
jQuery global

### ISSUE THREAD

**Issue by Yuriy-Karpov** [bem-site/bem-forum-content-ru#1149]
Приветствую, есть штатные средства объявить jQuery глобально? 
Возникла такая необходимость для back-end разработчиков, что бы они могли обращаться к $ без ym.

window.jQuery = window.$ = jQuery;

**Comment by kompolom** [comment]
Загрузите jQuery обычным способом до подключения ym

**Comment by Yuriy-Karpov** [comment]
@kompolom  спасибо, помогло, 
на всякий случай разъясню:
необходимо подключить как элемент page,
```
 {elem: 'js', url: '../../libs/jquery/dist/jquery.min.js'},
```
 а не через специализированные поле блока
```  
 scripts: [{elem: 'js', url: '../../libs/jquery/dist/jquery.min.js'}],
```

**Comment by lilliputten** [comment]
Хм... По-моему, безразлично как, главное, чтобы оно оказалось раньше, чем ym будет пробовать подключать jquery из bem-core.

**Comment by tadatuta** [comment]
А еще можно никак специально не подключать, а просто брать jQuery из модульной системы:
```js
modules.require('jquery', function($) {
    // тут пишем код, использующий jQuery
});
```
