### ISSUE TITLE
Плавный скрол к нужному блоку и вопрос про карты

### ISSUE THREAD

**Issue by webtehnology** [bem-site/bem-forum-content-ru#1171]
Подскажите как правильно связать ссылки в меню на соответсвующие блоки на этой же странице?
Имено правильно описать зависимость( до изучения бэм  использовал id)

Второй вопрос, установил https://github.com/tadatuta/ymaps-and-bem 
вопрос рабочий ли вариант это?

**Comment by tadatuta** [comment]
@webtehnology Если речь о том, чтобы реализовать якоря на странице, то стоит продолжать использовать `id` — это один из редких случаев, когда использование `id` полностью оправдано ;)

> ymaps-and-bem

Возможно, проект и заведется, но он в любом случае достаточно устарел в плане кода — прошло 3 года с тех пор, как он последний раз обновлялся.

Самый актуальный «стартер-кит» — это https://github.com/bem/project-stub

**Comment by webtehnology** [comment]
Я поставил блоки  из сдорки в свой проект, карта так и не появляется, думал не подтягивается библиотека или устрела, пробовал тнапрямую рабочую билиотеку карт подтянуть, но всёравно нет инициализации карты, поэтому и спросил рабочий ли сам пример с картами(именно блоки)

**Comment by webtehnology** [comment]
Загрузка библиотеки заработала, по сути все просто. Но не происходит инициализация карты. Пробовал через id, не катит
```
{
                                    block:'map',
                                    mods: { api: 'ymaps' },
                                    js: true,
                                    attrs: { id: 'map', }
}
```
Файл js, как я понимаю нужно сначала инициализировать блок, потом уже загружать карту 

как делаю в обычных случаях 
```
 <script>
	ymaps.ready(function () {});
 </script>
```

```
modules.define('map', ['i-bem__dom'], function(provide, BEMDOM) {
provide(BEMDOM.decl(this.name, {
    onSetMod: {
        'js' : {
            
            'inited' : function() {
               this.loadMapsApi();     
            }
        }
    },
    loadMapsApi: function () {
     	var elem = document.createElement('script');
    	elem.src = ['https://api-maps.yandex.ru/2.0.29/?load=package.full&lang=ru-RU'];
      	document.body.appendChild(elem);
	this.onAPILoaded();
    },
    onAPILoaded: function () {
        this.initMap();
        
    },
    initMap: function () {
    	//alert('Запустили')
    // Инициализация карты
        this._map = new ymaps.Map(this.domElem[0], {
            center: [55.74438877721849,37.563853499999986],
        	type: "yandex#map",
        	zoom: 17,
        });
        
    }
},
));
});;


```
