### ISSUE TITLE
Отловить элемент при помощи match в bemhtml

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1178]
Хочу в шаблоне выбрать (по имени) вложенные в блок элементы и... ч.-ндь к ним применить.

Вижу, что в `match` у меня `this.elem` всегда `undefined`, а `elemMatch` (про который где-то что-то попадалось) почему-то отсутствует.

Как правильно поступить?

**Comment by tadatuta** [comment]
А откуда задача делать это именно через match?

Такие варианты не подойдут?
```js
block('b1').elem('e1') // если нужен конкретный элемент
block('b1').elem('*') // если нужен любой
```

Если же нужно получить имя полученного элемента, то оно будет лежать в `this.elem` в теле шаблона.

**Comment by lilliputten** [comment]
@tadatuta Ах, да! Забыл дополнить, что нужно соответствие "по маске". :)) Т.е., банальный `elem`, к сожалению, не подходит. В принципе, приспособив некоторые костыли, мог бы обойтись `elem('*')`, но он, как выяснилось, тоже [не работает](https://github.com/bem-site/bem-forum-content-ru/issues/1147).

Т.е., нужен именно доступ к `this.elem` внутри `match` или что-то вроде.

**Comment by tadatuta** [comment]
Проблему с тем, что звездочка в элементах матчится на все блоки можно закостылять через https://goo.gl/PBPzbi

А `this.elem`, конечно, доступен в `match`, но только в том случае, когда он определен. Другое дело, что если написать `block('b1')` и не писать предикат про `elem()`, то `bem-xjst` автоматически отфильтрует все узлы про элементы, поэтому в `match` после предиката про блок и не будет `this.elem`. Проверить легко — достаточно написать что-то типа
```js
block('b1').elem('e1')
    .match(function() { console.log(this.elem); return true; })
    .content()(function() {
        return this.elem;
    });
```

**Comment by zxqfox** [comment]
@lilliputten Тот баг обходится вполне: `block('some').elem('*').match(function(){ return this.block === 'nuzhnyj-block' && this.elem === 'nuzhnyj-element'; }).content()('asd');`

**Comment by tadatuta** [comment]
@zxqfox я это как раз и привел в примере по ссылке выше ;)
