### ISSUE TITLE
Отловить элемент, вложенный в блок с модификатором в bemhtml

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1187]
Здача: матчить элемент блока с модификатором.
Вроде бы должно быть так ведь: `block('b').mod('m', true).elem('e')( ... );`?
Сам по себе блок+мод отлавливается замечательно: `block('b').mod('m', true)`. Аналогично -- вложенный элемент `block('b').elem('e')( ... );`.
Но всё вместе никак почему-то не удаётся.
Что я делаю не так?

**Comment by tadatuta** [comment]
Должно работать именно так, вот демка: https://goo.gl/p7qhNJ

**Comment by lilliputten** [comment]
Только что понял, в чём дело. Мне тоже как-то казалось, что я прав. %) Два часа тупого пяленья на код и пустых переделок всё-таки дали результат. Дело банальное до крайности (как обычно):

Дело в том, что часть кода у меня создаётся динамически (меняем/добавляем элементы внутри уже созданного блока через `BEMHTML.apply(...)`) и вот там в шаблоны отдаётся `elem : <имя_элемента>` и `block : <имя_блока>`, чтобы было понятно, откуда брать шаблон. О том, что шаблону неоткуда узнать об имеющихся в уже сгенерённом блоке модификаторов, никто не подумал.

Поёду цеплять модификаторы. %))

**Comment by lilliputten** [comment]
Ещё чуть-чуть: А как при такой схеме правильно расклдывать файлы бэм в дереве файловой структуры? Предполагал, что для описанного случая (пытаюсь группировать элементы блока с определённым модификатором), должно было быть что-то вроде:
```
block/
    block.*
    _mod/
        block_mod.*
        __elem/
            block_mod__elem.*
```
-- Но по факту не работает.

Единственный ли выход -- валить всё в `block/_mod/block_mod.*` без группировки по отдельным сущностям?

В [подсказке по организации файловой структуры](https://ru.bem.info/methodology/filestructure/#nested) ничего подходящего вроде бы находится...

**Comment by yar-usenko** [comment]
Это тот же `block('b1').mod('m1', true).content()('works!')`, только ты меняешь контент не блоку, а элементу блока. Поэтому, в nested файловой структуре, расположение шаблона будет `b1/_m1/b1_m1.bemhtml.js`

**Comment by lilliputten** [comment]
@yar-usenko Имелось в виду, существует ли возможность разложить элементы по файлам/папкам уже внутри описания мода. Напр.:
```
b1/
    ...
    m1/
        b1_m1__e1.*
        b1_m1__e2.*
        ...
    ...
```

**Comment by tadatuta** [comment]
Сейчас готовой такой схемы нет, но в теории она может быть произвольная.
Хотя в данном случае `b1/_m1/b1_m1.*` вроде вполне логичный вариант.
