### ISSUE TITLE
Как к кнопке примиксовать элемент?

### ISSUE THREAD

**Issue by Index1** [bem-site/bem-forum-content-ru#1211]
Имеется стандартный JSON кнопки ->
`block : 'button',
 mods : { theme : 'islands', size : 'm', view : 'action'},
 text : 'Создать'`
В html мы получаем: `<button class="button button_theme_islands button_size_m button_view_action button__control i-bem button_js_inited" data-bem="{&quot;button&quot;:{}}" role="button" type="button"><span class="button__text">Создать</span></button>`. К данному html мне нужно ещё добавить элемент к JSON чтобы в конечном результате в html вышло:
`<button class="button button_theme_islands button_size_m button_view_action button__control button__add-form i-bem button_js_inited" data-bem="{&quot;button&quot;:{}}" role="button" type="button"><span class="button__text">Создать</span></button>`.

**Comment by tadatuta** [comment]
```js
{
    block : 'button',
    mods : { theme : 'islands', size : 'm', view : 'action'},
    mix: { elem: 'add-form' },
    text : 'Создать'
}
```

**Comment by Index1** [comment]
Спасибо) А вот такой вопрос, возможно ли сделать так, чтобы к примеру, когда добавили микс и в html было не button__add-form, а скажем, folders__add-form,

**Comment by tadatuta** [comment]
```js
{
    block : 'button',
    mods : { theme : 'islands', size : 'm', view : 'action'},
    mix: { block: 'folders', elem: 'add-form' },
    text : 'Создать'
}
```
