### ISSUE TITLE
Не работает пример "Собираем статическую страницу"

### ISSUE THREAD

**Issue by alosev** [bem-site/bem-forum-content-ru#1226]
Добрый вечер!

Проблема во в чем - не работает js на блоке hello. Все прописано по примеру, но блок даже не инициализируется, т.е. i-bem у него появляется, а вот js-inited нет, соответственно не работает кнопка как должна.
Может там что-то изменилось и как-то по другому нужно делать? 

В блоке input подключается модуль [i-bem-dom], а в примере [i-bem__dom]. Если ставить такой, то инициализация проходит, но вываливает ошибку по методу findBlocksInside.

**Comment by tadatuta** [comment]
Привет!

Страница уже обновлена в репозитории, но еще не доехала до сайта: https://github.com/bem-site/bem-method/blob/bem-info-data/articles/quick-start-static/quick-start-static.ru.md

**Comment by alosev** [comment]
Благодарю!

Сейчас завелось, но...ругается на метод getVal(), говорит, что нет такого у this._input

P.S.: там в описании еще небольшая неточность http://joxi.ru/a2XewdoTBaBMAg

**Comment by tadatuta** [comment]
@alosev спасибо, поправил: https://github.com/bem-site/bem-method/commit/ccfac276050f302ea4a56f6462c1dec30900dcdb
Кстати, есть подозрение, что с этой правкой и `getVal()` заведется.

**Comment by alosev** [comment]
Да, премного благодарен, работает!
