### ISSUE TITLE
Сборка проекта с webpack?

### ISSUE THREAD

**Issue by Integer64** [bem-site/bem-forum-content-ru#1227]
Здравствуйте. Сверстал проект использую за основу project-stub и сборщик enb. Появилась необходимость собирать проект используя webpack. Подскажите как сделать сборку через webpack? И как настроить enb для сборки merged бандла только для сборки стилей в один файл?

**Comment by tadatuta** [comment]
> Подскажите как сделать сборку через webpack?

Нужно больше подробностей про задачу — чего именно хочется добиться с помощью webpack-а. Возможно, это будет проще сделать используя `ENB` или совмещая оба сборщика.

> как настроить enb для сборки merged бандла только для сборки стилей в один файл?

За основу стоит взять ветку https://github.com/bem/project-stub/tree/merged и перенести `'?.min.js'` со строки https://github.com/bem/project-stub/blob/merged/.enb/make.js#L126 на следующую строку (положить в массив рядом с `'?.html'`).

**Comment by Integer64** [comment]
Привет, спасибо за быстрый ответ. Сейчас верстка собирается и обновляется при помощи enb в одной ветке, трудность в том что в другой, dev ветке(сажается верстка), используется только laravel-elixir для сборки. Приходится в ручную переносить скомпилированные js и стили бандлов с одной ветки в другую, а затем их подключать используя require         
```
if($('.page_categories').length) {
            require.ensure([], require => {
                require('../bem/js/categories.min.js');
            });
        }
```
Хотелось бы собирать все в одном месте. Организовать сборку только на enb нет возможности.

**Comment by tadatuta** [comment]
Предлагаю организовать сборку так, чтобы сначала выполнялась сборка на `ENB`, а следом вызывался `webpack` — это будет и проще, и быстрее в использовании.
