### ISSUE TITLE
Проброс атрибутов в __control компонентов.

### ISSUE THREAD

**Issue by gwer** [bem-site/bem-forum-content-ru#1240]
Для воплощения самых неожиданных фантазий понадобилось уметь пробросить собственные атрибуты (не произвольные, определённый перечень) элементу `__control` компонентов из `bem-components`.

Как наиболее канонично это сделать? 

В принципе, через свой уровень переопределения с прокачкой списка атрибутов из `applyNext()` оно работает. И вроде даже ничего ломать не должно.
Но есть ли возможность провернуть то же самое, используя обёртку?

Создать, например, блок `my-input`, который внутри себя использует блок `input` из `bem-components`.
И чтобы в тег `input`, который `input__control`, можно было пробросить некоторый атрибут `my-attr`.

**Comment by tadatuta** [comment]
@gwer Можно, например, так:

```js
block('my-input').content()(node => {
    // взводим флаг, доступный во всех узлах, вложенных в my-input
    node._inMyInput = true;

    return {
        block: 'input',
        mods: { theme: 'islands', size: 'm' }
    };
});

// всем input__control, у которых оказался взведен флаг, расширяем атрибуты
// важно гарантировать, чтобы базовый шаблон `input__control` оказался раньше (стоит подключать по mustDeps)
block('input').elem('control').match(node => node._inMyInput).attrs()((node, ctx) => {
    return node.extend(ctx, { myAttr: true });
});
```

**Comment by gwer** [comment]
Выглядит как то, что надо. Вот только я попробовал и немножко поплохело.

Сначала посыпались эксепшоны про неумение в стрелочные функции с отсылками к esprima (запускается под Node.js 6.9). Когда переписал на старые функции, оно отказалось работать с аргументами.

То есть внутри `function(node) {}` `node` отдаёт `undefined`, при этом в `arguments` всё хорошо (для проверки примера заменил все `node` на `arguments[0]` и `ctx` на `arguments[1]`, и всё завелось). 

Это последствия использования generator-bem-stub или такое встречается на каждом шагу?

**Comment by tadatuta** [comment]
Ой-ей-ей, если еще не слишком поздно, стоит срочно съехать с `generator-bem-stub` на https://github.com/bem/project-stub/ или https://github.com/bem/bem-express/
Генератор устарел чуть более, чем полностью :(

**Comment by gwer** [comment]
Окау, попробую.
