### ISSUE TITLE
ошибка  - can't resolve dependence "BEMHTML"

### ISSUE THREAD

**Issue by webtehnology** [bem-site/bem-forum-content-ru#1260]
Добрый день!
Выдается такая ошибка
`Module "profit-metal": can't resolve dependence "BEMHTML"`

при подключении технологии в файле js
`modules.define('profit-metal', ['i-bem-dom','BEMHTML', 'jquery'], function(provide, bemDom, BEMHTML, $) `

кэш чистил, пробовал такой вариант, ошибка весит.
```
({
    tech : 'js',
    mustDeps : [
        { tech : 'bemhtml', block : 'i-bem' }
    ]
})
```

**Comment by tadatuta** [comment]
С версии `bem-xjst 2.x` добавлять зависимость от блока `i-bem` нет необходимости — базовые шаблоны были внесены в ядро.

Но судя по ошибке, ядро в принципе не попадает в клиентский JS. Так что смотреть нужно где-то в районе `.enb/make.js` примерно на эти строки: https://github.com/bem/project-stub/blob/master/.enb/make.js#L78-L98

**Comment by webtehnology** [comment]
Собираю через gulp. А в файле `make.js` этот кусок кода такой же

```
gulp.task('build', () => {
    return bundler('*.bundles/'+ project + '/')
        .pipe(builder({
            css: bundle =>
                bundle.src('css')
                    .pipe(stylus())
                    .pipe(postcss([
                        autoprefixer({
                            browsers: ['ie >= 10', 'last 2 versions', 'opera 12.1', '> 2%']
                        }),
                        postcssUrl({ url: 'inline' })
                    ]))
                    .pipe(csso())
                    .pipe(concat(bundle.name + '.min.css')),
            js: bundle =>
                merge(
                    gulp.src(require.resolve('ym')),
                    bundle.src('js').pipe(filter(f => ~['vanilla.js', 'browser.js', 'js'].indexOf(f.tech))),
                    bundle.src('js').pipe(filter(file => file.tech === 'bemhtml.js'))
                        .pipe(concat('browser.bemhtml.js')).pipe(bemhtml())
                )
                    .pipe(uglify())
                    .pipe(concat(bundle.name + '.min.js')),
            tmpls: bundle =>
                bundle.src('bemhtml')
                    .pipe(concat('any.bemhtml.js'))
                    .pipe(bemhtml())
                    .pipe(concat(bundle.name + '.bemhtml.js')),
            html: bundle => {
                const bemhtmlApply = () => toHtml(bundle.target('tmpls'));
                return gulp.src(bundle.dirname + '/*.bemjson.js')
                    .pipe(bemhtmlApply());
                                        
            }
       }))

       .on('error', console.error)
       .pipe(debug())
       .pipe(gulp.dest(file => path.dirname(file.path)));       
});
```

**Comment by tadatuta** [comment]
Проблему сборки клиентских шаблонов с помощью gulp подтверждаю, будем чинить:
https://github.com/bem/project-stub/issues/239

**Comment by zxqfox** [comment]
А точно, как временное решение, нельзя так:
```js
const wrap = require("gulp-wrap");

    // ...
    bundle.src('js').pipe(filter(file => file.tech === 'bemhtml.js'))
        .pipe(concat('browser.bemhtml.js')).pipe(bemhtml())
        .pipe(wrap([
            'modules.define(\'BEMHTML\', [], function(provide) {`,
            '    <%= contents %>',
            '    provide(BEMHTML);',
            '});'
        ].join('\n'), {}, { parse: false }))
    // ...
```

**Comment by webtehnology** [comment]
@tadatuta Вы не могли бы отписаться тут  по окончанию.

**Comment by webtehnology** [comment]
@tadatuta Не подскажите, вносились ли изменения. А то так и не разобрался, а технология нужна

**Comment by tadatuta** [comment]
@webtehnology будет в ближайшее время. можно следить за https://github.com/bem/bem-xjst/issues/375

**Comment by zxqfox** [comment]
Вот это нужно: https://github.com/bem/bem-xjst/pull/457/files

**Comment by trebushuk** [comment]
@tadatuta Что же все-таки решилось с этой проблемой?

**Comment by trebushuk** [comment]
Как всетаки сделать чтобы BEMHTML попадал в js бандл?

**Comment by webtehnology** [comment]
Проблема не решена и в последней версии, использую уже давно для сборки enb

**Comment by tadatuta** [comment]
@webtehnology @trebushuk Починили, наконец-то!
Простите, что так долго :(

**Comment by Karodar** [comment]
Нужно упомянуть что если данная ошибка встречается на Пользовательских блоках(во время их подключения через систему **YModules**). То достаточно добавить файл технологии **js** для подключаемой сущности, будь то _Элемент_ или _Блок_ (сам же на всякий случай создаю еще файл шаблона со **Стандартным режимом** _**{ js: true }**_)
