### ISSUE TITLE
Препроцессинг js в enb/borschik: включение файлов

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1275]
Не могу разобраться, как использовать нотацию `borschik:include:` в js-файлах.

Есть пример. Файл `a.js`:
```javascript
/* borschik:include:b.js */
```
Файл `b.js`:
```javascript
// test b
```
Если исопльзую просто borschik с командной строки, то всё работает:
```shell
borschik --input=a.js --minimize=no
```
-- всё работает ок. В составе enb сборки инструкция не обрабатывается.

Пытался подключать `js-borschik-include` в `.enb/make.js` для обработки отдельных исходных файлов, но либо не разобрался с особенностями конфигурации (обычная история), либо какие-то ещё дрова попались.

Включаю технологию:
```javascript
var
    // ...
    techs = {
        // ...
        borschikInclude: require('enb-borschik/techs/js-borschik-include'),
        browserJs: require('enb-js/techs/browser-js'),
        // ...
    },
    // ...
;
module.exports = function (config) {
    // ...
    config.nodes('pages/*', function(node) {
        node.addTechs([
            // ...
            [techs.borschikInclude, {
                sourceSuffixes : ['js'],
                target: '?.pre.js',
            }],
            [techs.browserJs, {
                sourceSuffixes: ['vanilla.js', 'js', 'browser.js'],
                sourcemap: true,
                includeYM: true,
            }],
            // ...
        ]);
    });
```
Что делаю не так?

Если правильно понимаю, мне надо заставить `borschikInclude` обрабатывать каждый js-файл (или файлы с определённым расширением) перед передачей в `browserJs`? Как?

Смотрел на:
- https://github.com/bem-site/bem-forum-content-ru/issues/679
- https://github.com/bem-archive/bem-articles/blob/master/borschik/borschik.ru.md
- https://github.com/borschik/borschik/blob/master/docs/js-include/js-include.ru.md
- https://github.com/enb/enb-borschik/blob/master/api.ru.md#js-borschik-include

**Comment by tadatuta** [comment]
В `project-stub` для js-бандлов `borschik` подключен из коробки: https://github.com/bem/project-stub/blob/master/.enb/make.js#L108

Чтобы инклюд работал из JS-кода блока, оформлено должно быть так:
Пусть у нас есть следующая структура на файловой системе.
```
common.blocks/
    b1/
        b1.js
        b.js
desktop.bundles/
    index/
        index.js
```

По зависимостям код из `common.blocks/b1/b1.js` попадет в `desktop.bundles/index/index.js`. И борщик будет запущен именно на `desktop.bundles/index/index.js`, так что путь от него до `b.js` будет выглядеть так: `../../common.blocks/b1/b.js`.

Соответственно, если мы хотим заинклюдить файл `b.js` из `b1.js`, необходимо в `b1.js` написать вот такой инклюд:
```
/* borschik:include:../../common.blocks/b1/b.js */
```

**Comment by lilliputten** [comment]
@tadatuta Понятно, да. Работает.

Немножко не удобно -- было бы логично инклюдить относительно расположения файла исходного блока. Идея запускать препроцессор до или внутри **browser-js** -- это утопия, да?

**Comment by tadatuta** [comment]
Почему утопия-то? Нужно просто запилить технологию по аналогии с https://github.com/enb/enb-borschik/blob/master/techs/borschik.js, но для работы с каждым исходным файлом вместо бандла. В качестве примера можно смотреть на https://github.com/enb/enb-borschik/blob/master/techs/js-borschik-include.js#L53

**Comment by lilliputten** [comment]
Как выясняется, помимо прочего, оно ещё и sourcemap ломает. В общем, видимо, к сожалению, не вариант для рабочих проектов. Увы.

**Comment by tadatuta** [comment]
Да, вечность назад была [попытка](https://github.com/borschik/borschik/pull/78) запилить поддержку сорсмапов в борщике, но ее так и не довели до конца :(
