### ISSUE TITLE
Не могу разобраться почему не отрабатывает js блока

### ISSUE THREAD

**Issue by satanicman** [bem-site/bem-forum-content-ru#1276]
Всем привет. Начал я знакомится с БЭМ, очень он мне понравился. Решил попробовать его вживую. Склонировал себе project-stub, установил зависимости. Все работает, все круто, все попробовал, кароче все супер. Но тут я дошел до i-bem js, думаю дай попробую написать что-то простенькое на нем. Взял блок:
<pre>{
    block: 'header',
    js: true,
    content: [
        'header content goes here'
    ]
}</pre>
В папке common.blocks создал как полагается папку header, положил туда header.js И написал туда самое простое что смог придумать:
<pre>console.log(1);
modules.define('header', ['i-bem__dom'], function(provide, BEMDOM) {
    provide(BEMDOM.decl(this.name, {
        onSetMod : {
            'js': {
                'inited': function () {
                    console.log('hello');
                    this.bindTo('click', function(e) {
                        console.log("Clicked!")
                    });
                }
            }
        }
    }));
});</pre>

Единица выводится, а вот hello и уж темболее clicked нет. В чем может быть проблема? Не знаю в какую сторону копать, может какая-то зависимость не установилась или в синтаксисе не разобрался. Не пойму...

**Comment by lilliputten** [comment]
М.б., не хватает
```javascript
        { block : 'i-bem', elem : 'dom', mods : { init : 'auto' } },
```
в зависимостях?

**Comment by satanicman** [comment]
Да я уже вроде бы как понял в чем проблема. Я подсмотрел в bem-components как там реализованы такие вещи. Как оказалось модуля i-bem__dom зависимостях нет, его либо переименовали а на bem.info еще не везде поменяли, но теперь он называется "i-bem-dom", либо я что-то не так делал и у меня он теперь так называется. Хотя я почитал статью ["Быстрый старт по созданию статической страницы"](https://ru.bem.info/platform/tutorials/quick-start-static/) и там он тоже по такому имени в зависимостях вызывается.

**Comment by tadatuta** [comment]
Да, этот туториал действительно опирается на предыдущую версию `bem-core`. Обновим, как только дойдут руки.
