### ISSUE TITLE
bem-textarea-editor: блок предоставляющий текстовый редактор

### ISSUE THREAD

**Issue by tadatuta** [bem-site/bem-forum-content-ru#1292]
Привет!

Мы работаем над новой версией этого форума и в процессе родилась библиотека [bem-textarea-editor](https://github.com/tadatuta/bem-textarea-editor) с блоком `editor`, позволяющим писать текст на маркдауне с удобной панелью инструментов (примерно как на github) и получать превью до отправки поста на сервер.

![](https://cloud.githubusercontent.com/assets/475746/24291461/1ab5c6b2-109a-11e7-889d-40588571e80d.png)

Получилось хорошо, поэтому мы решили опубликовать библиотеку в open source. Вдруг вам тоже пригодится? :)

Посмотреть на работу блока в действии можно [тут](https://tadatuta.github.io/bem-textarea-editor/).

**Comment by denisbalyko** [comment]
А над форумом в закрытую пока работаете?

**Comment by tadatuta** [comment]
@denisbalyko почему же? вот он https://github.com/tadatuta/bem-forum/
