### ISSUE TITLE
Как последнему элементу в наборе установить класс

### ISSUE THREAD

**Issue by kazakovaNet** [bem-site/bem-forum-content-ru#1302]
Добрый день! Начинаю изучать БЭМ (методологию и инструменты). В процессе практики возник следующий вопрос. Как на последний элемент в наборе навесить класс.
Есть меню с пунктами. Для последнего пункта нужен класс для особого оформления. Как это сделать в шаблонизаторе разобраться не могу. Подскажите, пожалуйста!

https://jsfiddle.net/8a6j3njg/

**Comment by tadatuta** [comment]
можно воспользоваться методом `isLast()`: https://goo.gl/98jB7p

**Comment by kazakovaNet** [comment]
спасибо! я сама нашла этот метод, но не разобралась как его применить. теперь все ок, класс добавляется. вопрос следующий, как правильно прописать зависимость, я сделала вот так, но сборщик все равно меня не понимает почему-то...
в файле top-menu__item.deps.js прописала 

({
    shouldDeps: [
        {mods: 'last'}
    ]
})

**Comment by tadatuta** [comment]
должно быть
```js
({
    shouldDeps: [
        { mods: { last: true } }
    ]
})
```
ну  и необходимо убедиться, что файл лежит по пути `top-menu/__item/top-menu__item.deps.js`

**Comment by kazakovaNet** [comment]
спасибо большое! а можно ли как то подменить текущий узел, при условии, что он является последним? в моем случае, присвоить модификатор last не самому элементу, а элементу, который находится в нем (ссылке)

**Comment by tadatuta** [comment]
если заменить, то
```js
block('top-menu').elem('item')(
    tag()('li'),
    attrs()(function () {
        return {href: this.ctx.url, role: 'link'};
    }),
    match(function() {
        return this.isLast();
    }).replace()('заменяем последний')
);
```

а если повлиять на ссылку внутри последнего айтема, то:
```js
block('top-menu')(
    elem('item')(
        tag()('li'),
        attrs()(function () {
            return {href: this.ctx.url, role: 'link'};
        }),
        match(function() {
            return this.isLast();
        }).extend()({ _isLast: true }) // поле _isLast будет доступно всем дочерним узлам
    ),
    elem('text')(
        elemMods()(function() {
            return { last: this._isLast };  
        })
    )
);
```

**Comment by kazakovaNet** [comment]
да, здорово. все работает! 
последний вопрос. в какую директорию следует положить этот шаблон - в блок top-menu, так как в нем упоминаются оба его элемента или в элемент item, так как основные манипуляции с ним происходят?

**Comment by tadatuta** [comment]
если в текущем виде, то однозначно в `top-menu`, но если какой-то из блоков опционален, то есть смысл вынести его шаблон отдельно и положить в файл элемента.

**Comment by kazakovaNet** [comment]
еще раз большое всем спасибо! =)
