### ISSUE TITLE
Gulp vs ENB

### ISSUE THREAD

**Issue by Novamoscow** [bem-site/bem-forum-content-ru#1304]
В каких случаях стоит использовать галп, а в каких enb?
 
Что выбрать для постоянного использования?

**Comment by tadatuta** [comment]
Если нет предпочтений, то я бы рекомендовал ENB.

**Comment by Novamoscow** [comment]
@tadatuta а если мне ещё нужно postCSS пересобрать в CSS. Или подключить другие полезные плагины. 
И вообще да, в чем отличие, хотелось бы узнать подробнее. Или, почему использовать enb вместо gulp

**Comment by zxqfox** [comment]
@Novamoscow enb используется в продакшне много лет, а сборку с Gulp еще не обкатали. Еще в Gulp нет готовых решений для i18n, сборки клиентского bemhtml, и т.п. В общем, с enb будет меньше проблем про БЭМ-стек.

**Comment by tadatuta** [comment]
Сейчас более-менее можно считать, что сборщики взаимозаменяемые, так что в первую очередь это вопрос предпочтений.
Со сборкой на gulp-е есть какое-то количество шероховатостей, но они потихоньку исправляются.

В целом ENB «заточен» под БЭМ, `gulp` универсальный таск-раннер. Поэтому, как верно написал выше @zxqfox, БЭМ-специфика на ENB будет работать шустрее и надежнее. При этом есть возможность из сборки на `gulp` позвать ENB. Основное преимущество `gulp`-а — распространенность и наличие разных плагинов. Впрочем, под ENB, кажется, все осмысленное уже тоже написано.

Я могу предложить какую-то такую схему выбора:
* если на проекте уже используется ENB, то ENB
* если на проекте уже используется gulp, то gulp
* если проект новый и нет никаких предпочтений, то ENB
* если проект новый, но есть опыт с одним из сборщиков, то можно брать его
