### ISSUE TITLE
Как реализовать добавление различных модификаторов к элементам в зависимости от модификатора блока?

### ISSUE THREAD

**Issue by kazakovaNet** [bem-site/bem-forum-content-ru#1305]
Добрый день! Задумала сделать обобщенный блок меню, с различными модификаторами, меняющими внешний вид как блока, так и элементов в нем. Наткнулась на ситуацию, когда больший вес для шаблонизатора имеет последнее указанное правило и он не хочет проверять оба сразу. Как быть?

https://goo.gl/wza4HK

**Comment by tadatuta** [comment]
Следует испольова add*-режимы: https://goo.gl/gRtllN

**Comment by kazakovaNet** [comment]
спасибо! 
подскажите еще пожалуйста, а как правильно указать приоритеты модификаторам, если в них есть одинаковые правила (например, размеры полей). В моем случае, нужно чтобы модификатор _last был весомее модификатора темы.
вот такая зависимость не помогает https://goo.gl/j5R4Pj

**Comment by tadatuta** [comment]
Если шаблоны написаны в одном файле, то нужно просто записать их в правильном порядке, чтобы более весомые оказались ниже.

Если же шаблоны написаны в разных файлах, можно воспользоваться `mustDeps`: в файле `nav/_theme/nav_theme.deps.js` написать
```js
({
    mustDeps: { mods: { last: true } }
})
```
Эта запись означает «подключить перечисленные в поле `mustDeps` зависимости строго до кода сущности, в которой записан такой deps.

**Comment by kazakovaNet** [comment]
Ни первый, ни второй вариант почему-то не сработали.
В nav__text_theme.deps.js положила зависимость:
`({
    block: 'nav',
    elem: 'text',
    mod: 'theme',
    val: 'orange',
    mustDeps: {mods: {last: true}}
})`

JSON и шаблон (ссылку не дает скопировать, видимо слишком длинная) [https://yadi.sk/i/OHdkBOBl3GYRyo](url)
