### ISSUE TITLE
Почему не удается достучаться до вложенного блока при указании модификатора?

### ISSUE THREAD

**Issue by kazakovaNet** [bem-site/bem-forum-content-ru#1307]
Добрый день! Не понимаю почему в первом случае микс успешно работает, а если добавлять условие через модификатор, то уже нет. Что не так делаю?

https://clck.ru/AsfzY

**Comment by tadatuta** [comment]
@kazakovaNet такой синтаксис для вложенности не работает.
такую задачу можно решать так:
```js
// ставим флаг _inOrangeFooter, доступный во всех потомках
block('footer').mod('theme', 'orange').extend()({ _inOrangeFooter: true });

// проверяем, что данный link имеет флаг _inOrangeFooter
block('link').match(function() { return this._inOrangeFooter; })(
    addMods()({ theme: 'orange' }),
    addMix()(function() {
        return {
            block: 'footer',
            elem: 'link',
            elemMods: {
                theme: 'orange'
            }
        };
    })
);
```

**Comment by tadatuta** [comment]
cc @miripiruni

**Comment by kazakovaNet** [comment]
Спасибо! =)

**Comment by kazakovaNet** [comment]
Возвращаюсь к проблеме. Не получается прописать зависимость для блока link от модификатора theme_orange. В файле link.deps.js прописываю:
`({
    shouldDeps: [{
        block: 'footer', elem: 'link', elemMods: {theme: 'orange'}
    }]
})`
При этом зависимость для footer__link срабатывает, а для footer__link_theme_orange нет. Что не так?

**Comment by kazakovaNet** [comment]
Сама разобралась. Ошибка в синтаксисе
`mods`, а не `elemMods`
