### ISSUE TITLE
BEMHTML.apply возвращает пустой результат

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1318]
Собственно постепенно осваиваю технологию и столкнулся с такой проблемой, что не могу динамически вставить какой-либо блок.
```js
    modules.define('app-menu', ['BEMHTML', 'i-bem-dom'], function(provide, BEMHTML, bemDom) {

    provide(bemDom.declBlock(this.name, {
    onSetMod: {
        js: {
            inited: function() {
                this._domEvents().on('click', this._addBlock);
            }
        }
    },
    
    _addBlock: function () {
        console.log(BEMHTML.apply({
            block: 'button',
            text: 'Submit'
        }));
    }
    }));

    });
```
BEMHTML.apply почему-то не возвращает блок button, подскажите в чем я не прав?

**Comment by zxqfox** [comment]
Могу предположить, что на клиент не приехали шаблоны. Сами шаблоны можно проверить подключив их из ноды: в терминале запускаем node, делаем там require('path/to/bundle.browser.bemhtml.js'), и пытаемся сделать apply(bemjspn)

**Comment by tadatuta** [comment]
Да, скорее всего действительно не приехали шаблоны на клиент.

Решение см. в https://ru.bem.info/forum/1220/#comment-273629069
