### ISSUE TITLE
Получить BEM-дерево из JSON

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1321]
Опишу примерно задачу.

Мы получаем ajax данные в виде обычного json (сервер php).
Например это список постов, соответственно у нас есть блок post, описанный в bemhtml.
Вопрос - как преобразовать голые json-данные в BEM-дерево на клиенте?
Схема насколько я понимаю должна быть JSON --> BEMTREE --> BEMHTML --> HTML, но разобраться пока не могу.

**Comment by tadatuta** [comment]
Да, схема верная.

Вопрос слишком общий, чтобы мочь посоветовать что-то конкретное.
Но в общем случае нужно собрать BEMTREE- и BEMHTML-шаблоны, подключить их на клиент, а зачем вызывать:
```
var html = BEMHTML.apply(BEMTREE.apply(data)); // где data — это данные с сервера, а в html окажется строка, которую можно будет вставить в DOM
```

**Comment by Kundin** [comment]
Указываю в качестве зависимости модуля BEMTREE - выдает   Error: Module "app": can't resolve dependence "BEMTREE"
Раскомментировал в .enb/make.js строчки, относящиеся к bemtree (нужно ли?) - пересобрал, результат тот же. Как правильно подключить? BEMHTML подключается нормально

**Comment by Kundin** [comment]
Как подключить BEMTREE и BEMHTML на клиент?
