### ISSUE TITLE
Неполная генерация block: 'image'

### ISSUE THREAD

**Issue by ax2mx** [bem-site/bem-forum-content-ru#1322]
Добрый день.

В примере по созданию проекта на БЭМ (https://ru.bem.info/platform/tutorials/start-with-project-stub/), на шаге добавления картинки в блок logo, фрагмент определения блока image из примера на сайте выглядит так:
```
            block: 'image',
            attrs: { src: 'some-url' }
```

При этом в результате сборки в html попадает только:
           `<img class="image">`

По аналогии с другими блоками попробовал переписать определение так:
```
            block: 'image',
            url: 'some-url'
```

И получилось ожидаемое: 
           `<img class="image" src="some-url">`

Подскажите, в чём здесь дело?

**Comment by DjonyBastone** [comment]
Обратите внимание на **актуальность версий** инструментов и библиотек:

enb v**1.3.0**
bem-core v**4.1.1**



А если воспользоваться примером из [bem-components](https://ru.bem.info/platform/libs/bem-components/5.0.0/desktop/image/#url)
```
{
    block : 'image',
    url : 'https://img-fotki.yandex.ru/get/5405/259818507.0/0_130be5_948d59aa_S'
}
```
то в `html` придет:
```
<img class="image" src="https://img-fotki.yandex.ru/get/5405/259818507.0/0_130be5_948d59aa_S" />
```
Проверено на большом количестве картинок. Постоянно на своем проекте пользуюсь этим блоком

может что-то **не верно** указали в `bemjson` ?

Пример :
```
                                    }
                                        block: 'main`,
                                        elem: 'content' : [
                                            {
                                                elem: 'img-layout',
                                                content : [
                                                    {
                                                        block : 'image',
                                                        mix : { block : 'bim', elem : 'background-image' },
                                                        url : '../../_bufer/image/mac_mockup.png'
                                                    },
                                                    {
                                                        elem : 'img-sub-layout',
                                                        content : {
                                                            block : 'image',
                                                            mix : { block : 'bim', elem : 'image' },
                                                            url : '../../_bufer/image/bim_img.jpg'
                                                        }
                                                    }
                                                ]
                                            }
                                        ]
                                    }
```

##По своему опыту - этот учебный проект и у меня не сработал)))
Установил последнюю версию project-stub
Потом мучился откатывал версии, ставил старые....
Плюнул и на новой версии стартанул проект, пользуясь [документацией](https://ru.bem.info/platform/libs/bem-components/5.0.0/) 
Всё запустилось.
еще немного помог блог [Ромы](http://www.webhive.ru)

**Comment by ax2mx** [comment]
Спасибо! Разобрался вроде :-)

**Comment by tadatuta** [comment]
Все так, баг даже уже [исправлен в исходниках](https://github.com/bem-site/bem-method/commit/fd9497b6e89ffb7089163e12b5840cf58d383976), но пока не доехал до сайта :(
