### ISSUE TITLE
Описание методов, событий i-bem

### ISSUE THREAD

**Issue by DjonyBastone** [bem-site/bem-forum-content-ru#1323]
Всем привет!! 
Подскажите существует ли список где можно увидеть все методы и события блока i-bem  и i-bem-dom?
Тяжело перелопачивать руководство, и крайне не удобно.

**Comment by tadatuta** [comment]
По задумке они предполагались здесь: https://ru.bem.info/platform/libs/bem-core/4.1.1/desktop/i-bem/#jsdoc и, соответственно, здесь https://ru.bem.info/platform/libs/bem-core/4.1.1/touch-pad/i-bem-dom/, но в этой версии мы сломали JSDoc для `i-bem-dom`, а новую пока не выкатили :(

**Comment by DjonyBastone** [comment]
Примерно так и предполагал. Думал что руки у вас не дошли.
В старых видео наблюдал, что JSDoc был. Обыскался сегодня его.
