### ISSUE TITLE
Помогите немного с формами

### ISSUE THREAD

**Issue by bemdev** [bem-site/bem-forum-content-ru#1324]
Привет, уважаемые дамы и господа!
дайте совет где я не прав
```js
modules.define('form', ['i-bem-dom'], function(provide, bemDom) {

provide(bemDom.declBlock(this.name, {
    onSetMod: {
        js: {
            inited: function() {
            }
        }
    }
},{
    getVal: function(){
        return this.domElem.serialize();
    }
}));

});
```

собственно все вроде просто но когда зову из другого блока 
```js
modules.define('post', ['i-bem-dom', 'form'], function(provide, bemDom, Form) {

provide(bemDom.declBlock(this.name, {
    onSetMod: {
        js: {
            inited: function() {
               var data = Form.getVal();
            }
        }
    }
}));

});
```
и вопрос номер два, можно ли как то искать блоки findChildBlock('input') как то так или нет обязательно требовать блок как модуль и его указывать ?

спасибо за ответы, не судите строго :%

**Comment by tadatuta** [comment]
@bemdev

Метод `getVal` должен быть объявлен у экзепляра, а не у класса (иначе непонятно, какую именно форму нужно сериализовать). И тогда ее потребуется сначала найти в DOMе, а затем уже вызывать метод:

```js
modules.define('post', ['i-bem-dom', 'form'], function(provide, bemDom, Form) {

provide(bemDom.declBlock(this.name, {
    onSetMod: {
        js: {
            inited: function() {
               var data = this.findChildBlock(Form).getVal();
            }
        }
    }
}));

});
```

Вроде это отвечает и на второй вопрос?

**Comment by bemdev** [comment]
Да, спасибо за оперативность!
