### ISSUE TITLE
Шаблонизация на клиенте

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1331]
Расскажите, пожалуйста, более подробно про шаблонизацию на клиенте, используя `project-stub`
Подключаю к странице файл `index.bemhtml.js`, в котором содержится шаблон *button*, значит на клиент все подгрузилось.
Затем пишу блок test
test.js
```js
    modules.define('test', ['BEMHTML', 'i-bem-dom'], function(provide, bemHtml, bemDom) {
        provide(bemDom.declBlock(this.name, {
            onSetMod: {
                js: {
                    inited: function() {
                        var html = bemHtml.apply({
                        	block: 'button',
                        	content: 'test'
                        });
                        console.log(html); // Возвращает пустой результат
                    }
                }
            }
        }));
    });
```
test.deps.js
```
    ({
	    mustDeps: [
	        { block: 'button' }
        ]
    })
```
Использовал *[bem-bemtree-static-project-stub](https://github.com/tadatuta/bem-bemtree-static-project-stub)* и все работало, то есть получается весь мой ступор в файле `enb/make.js`

**Comment by Kundin** [comment]
a

**Comment by tadatuta** [comment]
@Kundin удалось разобраться?
