### ISSUE TITLE
Как правильно подвязать уровень?

### ISSUE THREAD

**Issue by bemdev** [bem-site/bem-forum-content-ru#1334]
День добрый!

Пишу тут разную мелочовку пробую тестирую, и вот не пойму как правильно уровень зацепить вот пример.
```js
enbBemTechs = require('enb-bem-techs'),
    levels = [
        { path: 'node_modules/bem-core/common.blocks', check: false },
        { path: 'node_modules/bem-core/desktop.blocks', check: false },
        { path: 'node_modules/bem-components/common.blocks', check: false },
        { path: 'node_modules/bem-components/desktop.blocks', check: false },
        { path: 'node_modules/bem-components/design/common.blocks', check: false },
        { path: 'node_modules/bem-components/design/desktop.blocks', check: false },
        { path: 'node_modules/bem-font-awesome-icons', check: false },
        'common.blocks'
    ];
```
я так понял тут они и пишутся, только вот добавляю иконки а они чет не приезжают :) 

вот зависимости
```js
({
	mustDeps: [
		{ block: 'icon' }
	],
	shouldDeps: [
		{ block: 'button', mods: { type: 'link' } },
		'link',
	]
})
```
вот так я их зову
```js
{
				block: 'button',
				mods: { theme: 'islands', size: 'm', type: 'link', disabled: item.disabled, view: item.view },
				text: item.name,
				url: item.url,
				icon : { block: 'icon', mods: { bg: 'adress-book' } }
}
```

где я не прав? или где почитать подробно?

Спасибо.

**Comment by tadatuta** [comment]
Уровень подключен правильно, просто в зависимостях не хватает модификатора (ну и в данном случае достаточно будет только shouldDeps):
```js
({
	shouldDeps: [
		{ block: 'button', mods: { type: 'link' } },
		'link',
                { block: 'icon', mods: { bg: 'adress-book' } }
	]
})
```

**Comment by bemdev** [comment]
хм я пробовал и явно указывать модификатор, все равно не приезжает моя заветная иконка :) что еще может быть у меня не так?

b-nav это мой блок имеет зависимости 

({
	shouldDeps: [
		{ block: 'button', mods: { type: 'link' } },
		{ block: 'icon', mods: { bg: 'adress-book' } },
		'link',
	]
})
</code>

в bemtree у меня это

{
				block: 'button',
				mods: { theme: 'islands', size: 'm', type: 'link', disabled: item.disabled, view: item.view },
				text: item.name,
				url: item.url,
				icon : { block: 'icon', mods: { bg: 'adress-book' } }
}

если уровни правильные то все же должно быть)

**Comment by tadatuta** [comment]
Да, по коду выглядит так, что должно работать.

Есть возможность опубликовать проект или часть проекта, где воспроизводится проблема, на github?

**Comment by bemdev** [comment]
По большому счету, там клон bem express. Я думаю где то очень банальная моя ошибка... Постараюсь решить своими силами, спасибо за реакцию.

**Comment by bemdev** [comment]
я же говорю дело было не в бабине) address две dd :()
