### ISSUE TITLE
Инициализация блока

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1336]
Какие причины могут быть для того, чтобы блок не инициализировался?
В bemhtml указал `block('name').js()(true);`, добавился класс `i-bem` и атрибут `data-bem`, но вот класса `name_js_inited` нет и соответственно  JS не выполняется.

**Comment by tadatuta** [comment]
Возможно где-то в JS-реализации блока ошибка, которая не дает ему инициализироваться. Например, потерялся вызов `provide()`.

**Comment by Kundin** [comment]
JS создан с помощью `bem-create` и все на месте..

**Comment by Kundin** [comment]
modules.define('user', ['i-bem-dom'], function(provide, bemDom) {

    provide(bemDom.declBlok('user', {
    onSetMod: {
        js: {
            inited: function() {
            	alert('init');
            }
        }
    }
    }));

    });

**Comment by Kundin** [comment]
Понял свою ошибку, у примиксованных блоков нельзя же так делать, верно?)
Извините за беспокойство

**Comment by tadatuta** [comment]
Да, пока шаблоны на примиксованные блоки не применяются, ждем решения по https://github.com/bem/bem-xjst/issues/340

**Comment by belozer** [comment]
@Kundin можно, но только при миксе нужно не забывать миксовать и JS.

`block('my-base-block').mix()({ block : 'my-mixed-block', js : true })`
