### ISSUE TITLE
Тонкая настройка минификации css?

### ISSUE THREAD

**Issue by karalkou** [bem-site/bem-forum-content-ru#1339]
День добрый!

В конфиге есть вот такая строчка
```
[techs.borschik, { sourceTarget: '?.css', destTarget: '_?.css', tech: 'cleancss', minify: false }],
```
Интересуют поля tech: 'cleancss' и minify: false/true

Логично предположить, что для минификации используется cleancss. Но как он подтягивается? Можно ли его тонко настроить?
Хотелось бы научиться отключать некоторые опции минификации (как, например, опция mergeLonghand в cssnano)

Версия bem-core 3.0.1. Полный стек.

**Comment by tadatuta** [comment]
Если указывать `tech: 'cleancss'`, то действительно используется `cleancss`, а если поле не указано, то будет использован CSSO, который на данный момент эффективнее и шустрее. Подтягивается он на основе соглашения в `borschik`, по которому ищется соответствующий `npm`-пакет, начинающийся на `borschik-tech-`.

Можно прокинуть любые опции, которые поддерживает сам `cleancss` с помощью `{ techOptions: { cleancss: opts } }`, где `opts` — необходимые опции.

**Comment by karalkou** [comment]
Спасибо)
