### ISSUE TITLE
Не работает пример из документации

### ISSUE THREAD

**Issue by PavelZubkov** [bem-site/bem-forum-content-ru#1342]
Читаю документацию по шаблонизатору, застопорился на первом примере.
- [Синтаксис шаблонов/Предикат шаблона/подпридекат block(ссылка)][1]
- [Песочница с примером(ссылка)][2]
***
Пример. Подпредикат блока link:
```javascript
block('link')
```
Входные данные:
```javascript
[
    // на этот блок предикат вернет `true` и шаблон будет применён
    { block: 'link' },

    // на все следующие сущности предикат вернет `false` и шаблон не будет применён
    { block: 'para' },
    'link',
    { block: 'link', elem: 'text' }
]
```
***
Конкретного описания к подпридекату block не добавлено, но выше говорится:
>Для каждого узла входного дерева шаблонизатор проверяет условия, указанные в шаблонах. Эти условия называются подпредикатами и составляют предикат шаблона.
>Условия могут быть простыми — проверка имени блока/элемента или более сложными и составными — проверка значений произвольных полей в текущем узле BEMJSON.

Исходя из этого и комментариев в примере я понял, что в выводе должен быть только блок link, но этого не происходит ни в одной из версий шаблонизатора, предложенных в песочнице.

**Вопрос: где я ошибся?**
[1]: https://ru.bem.info/platform/bem-xjst/templates-syntax/#block
[2]: https://goo.gl/5zYtAs

**Comment by DjonyBastone** [comment]
Не совсем понятно что вы планируете в итоге получить. Какой в итоге код html должен получиться?
[работа с вашим кодом](https://goo.gl/IjPeYh)

**Comment by PavelZubkov** [comment]
@DjonyBastone спасибо за ответ. Я ожидал получить, только одну строку '<div class="link"></div>' - блок link, т.к. предполагал что предикат(и подпридекаты) являются "фильтрами" входных данных, такое представления сложилось из документации.

Это было заблуждением. Подпридекат - это селектор, по аналогии с CSS. Я правильно понял?

**Comment by DjonyBastone** [comment]
если говорить о движке `bemhtml` - да, верно!
`bemhtml` навешивает на сущность ожидаемое дополнение - тег, атрибуты, контент и т.д. Как на раму автомобиля устанавливаются все детали - двигатель обшивка, подвеска и т.д.
А в `bemjson` или `bemtree` указывается сама **сущность** - блок, элемент, контент...

В `bemjson` - можно и без `bemhtml` - тюнинговать. Так как принимает дополнения после указания блока или элемента. Такой подход оправдан для одноразового использования сущности, или прокидывания параметров дочерним элементам. Хороший пример блок `button` в `bem-components`

В `bemtree` - немного иначе. По моим ощущениям - для формирования скелета  страницы (рыба). То есть указать какие блоки/элементы есть и что в них содержится. Из названия понятно, для формирования БЭМ-дерева.

**Comment by PavelZubkov** [comment]
Спасибо!
