### ISSUE TITLE
Встраивание графики в css

### ISSUE THREAD

**Issue by beergreezen** [bem-site/bem-forum-content-ru#1345]
Разместил конфиг борщика в корне, чтобы кодировать все изображения, кроме SVG в base64.
Если  ```**/*.blocks/**```, то кодирует все изображения.
Но мне нужно, чтобы кодировалось все, кроме svg. Условие ```**/*.blocks/**/!(*.svg)``` не работает :(
Что я не так делаю?

Конфиг: 
```js
{
	"freeze_paths": {
	    "img/**": "img",
	    "**/*.blocks/**/fonts/**" : "fonts",
	    "**/*.blocks/**": ":encodeURIComponent:",
	    "**/*.blocks/**/!(*.svg)": ":base64:"
	}
}
```

**Comment by tadatuta** [comment]
конфиг не поддерживает отрицания, но позводяет задать для `svg` отдельное произвольное правило.

например, кодируем все в `base64`, а `svg` — с помощью `encodeURIComponent`:
```
"*.blocks/**/*.svg": ":encodeURIComponent:",
"*.blocks/**": ":base64:"
```

**Comment by beergreezen** [comment]
@tadatuta Спасибо! =)
