### ISSUE TITLE
может ли блок быть вложен в элемент?

### ISSUE THREAD

**Issue by webnarmin** [bem-site/bem-forum-content-ru#1346]
https://ibb.co/gs6brQ

есть у нас блок `faq`
который вложен в элемент списка `faq__list-item`
`faq__list-item` вложен в `faq__list`, `faq__list` вложен в `body`

допустимо ли это согласно концепции БЕМА?

**Comment by belozer** [comment]
@webnarmin поддерживаю Владимира.

Вкладывать блок в свои элементы не совсем правильная затея. У вас явное разделение на 2 сущности.

1. faq
2. список (элементами которых является faq)
