### ISSUE TITLE
Получить блок из элемента (BEMHTML)

### ISSUE THREAD

**Issue by sinitsyn-alex** [bem-site/bem-forum-content-ru#1371]
Есть блок с названием 'secondary-menu'. У него есть элемент 'top'. В элементе 'top' есть блок 'menu' с массивом 'items'.
Знания вынес в шаблон, прописал deps.
Но при обновлении страницы ничего не происходит. Я предполагаю, что в шаблоне после элемента 'top' не находит блок 'menu'. Можно ли использовать вложенность в шаблоне? 
Пример: block('secondary-menu').elem('top').block('test-block')...
```js
/* secondary-menu.bemjson.js */
module.exports = {
	block: 'secondary-menu',
	content: [
		{
			elem: 'top',
			content: {
				block: 'menu',
				items: [
					{
						title: 'Статьи',
						url: '/'
					},
					{
						title: 'Рецепты',
						url: '/'
					},
					{
						title: 'Новости',
						url: '/'
					}
				]
			}
		}
	]
};
```
Шаблон:
```js
/* secondary-menu.bemhtml.js */
block('secondary-menu').elem('top').block('test-block')(
	content()(function() {
		return this.ctx.items.map(function(item) {
			return {
				elem: 'item',
				content: {
					block: 'link',
					url: item.url,
					content: item.title
				}
			};
		});
	})
);
```
```js
/* secondary-menu.deps.js */
({
	shouldDeps: [
		{ elem: 'item' },
		{ block: 'link' },
		{ block: 'menu' },
		{ elem: 'top'}
	]
})
```

**Comment by tadatuta** [comment]
Вложенность в таком виде, как в приведенном сниппете кода — нельзя.
Но можно воспользоваться тем фактом, что поля, сохраненные в `this` в родителе будут доступны из всех потомков.

Т.е. можно написать так:
```js
block('secondary-menu').elem('top').extend()({ _inSecondaryMenuTop: true });

block('menu').match(function() { return this._inSecondaryMenuTop; })(
	content()(function() {
		return this.ctx.items.map(function(item) {
			return {
				elem: 'item',
				content: {
					block: 'link',
					url: item.url,
					content: item.title
				}
			};
		});
	})
);
```

Вот этот же пример в песочнице: https://goo.gl/Y2QfuF

**Comment by sinitsyn-alex** [comment]
Спасибо за ответ. А если у меня в secondary-menu два элемента: top и bottom? И для каждого нужно использовать свои входные массивы, как поступить тогда?

**Comment by sinitsyn-alex** [comment]
Так будет правильно? https://goo.gl/tK9eP5

**Comment by tadatuta** [comment]
У меня по приведенной ссылке открывается старый код, но если я правильно понял задачу из описания, то должно быть достаточно просто взводить флаг на самом блоке`secondary-menu` вместо конкретных элементов: `block('secondary-menu').extend()({ _inSecondaryMenuTop: true });`
