### ISSUE TITLE
Некорректная сборка блока menu в bh.php

### ISSUE THREAD

**Issue by sinitsyn-alex** [bem-site/bem-forum-content-ru#1392]
Есть страница:
/* index.bemjson.js */
```js
module.exports = {
    block: 'page',
    ...
    content: [
        {
            block: 'menu',
            mods: {
                theme: 'islands',
                size: 'm',
                mode: 'radio'
            },
            content: [
                {
                    elem: 'item',
                    content: 'Отдых в горах'
                },
                {
                    elem: 'item',
                    content: 'Отдых на море'
                }
            ]
        }
    ]
};
```
После построения, появляется блок menu -> 
в нем элементы item, но у них нет uniq и не меняются модификаторы (checked, hovered), так же отсутствует класс i-bem, атрибут data-bem .
Причем у блока menu появляется class i-bem, модификаторы, uniq и т.д.
У кнопок так же все функционирует и работает, а вот menu__item не хочет работать.
В либе ошибочка?(

**Comment by sinitsyn-alex** [comment]
@zxqfox help

**Comment by tadatuta** [comment]
Предположу, что проблема в конфигурации шаблонизатора (см. https://github.com/bem/bh#jscls)

**Comment by zxqfox** [comment]
Скорее всего дело в настройках да.
Ещё вопрос какая версия бэм-компонент используется, шаблоны вряд-ли часто обновляются

**Comment by sinitsyn-alex** [comment]
@zxqfox Проблема решена. 
Изначально использовали project-stub со всеми последними devDependencies. Откатили enb на более старую версию и всё заработало.
