### ISSUE TITLE
Насколько правильно использован БЭМ нейминг на данной странице?

### ISSUE THREAD

**Issue by IvanSolov** [bem-site/bem-forum-content-ru#1395]
Добрый день. Нужна оценка корректности БЭМ нейминга на данной странице: http://portfoliome.ru/demo/portland/
Верное ли наименование классов, использование миксов и тд?

**Comment by tadatuta** [comment]
При беглом осмотре выглядит вполне нормально. Разве что могу порекомендовать почитать [пост про обертки](https://ru.bem.info/forum/656/).
