### ISSUE TITLE
Добавить зависимость для юнит-тестов

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1402]
Для тестирования понадобилось использовать зависимость, которая не нужна самому блоку. Пытаюсь подключить как-то так (deps.js):
```javascript
([
{
    shouldDeps : [
        // ...
    ],
},
{
    tech : 'spec.js',
    shouldDeps : [
        { block : 'box' },
    ],
},
])
```
Здесь `box` -- именно то, что пытаюсь реквайрить в тесте:
```javascript
modules.define('spec', [ 'box' ], function(provide, box) { /* ... */ });
```
В результате всё равно получаю `Error: Module "spec": can't resolve dependence "box"`.

ЧДНТ?

**Comment by tadatuta** [comment]
Пара вопросов:
1. Точно ли все хорошо с декларацией в `box.js`? Не потерялся ли там вызов `provide()` например?
2. Попал ли в итоге код из `box.js` в бандл с тестами?

**Comment by veged** [comment]
1. нужно указывать вторую технологию (которую хочется использовать):
```js
...
{
    tech : 'spec.js',
    shouldDeps : { tech : 'js', block : 'box' }
}
...
```

2. нужно убедиться, что box.js существует и там есть `modules.define('box'...`

**Comment by lilliputten** [comment]
@tadatuta Да, вот так, -- с `tech : 'js'` -- заработало. (Пробовал аналогичное, но вместо `js` пытался `browser-js`...)
