### ISSUE TITLE
Доопределение поведения в библиотечном блоке Attach. Ошибка

### ISSUE THREAD

**Issue by sinitsyn-alex** [bem-site/bem-forum-content-ru#1411]
Всем доброго времени суток.
Появилась необходимость доопределить js для блока Attach.
А именно, при выборе картинки рисовать preview аватара.
Код: 
```js
/* desktop.blocks/attach/attach.js */
modules.define('attach', function(provide, Attach) {
	provide(Attach.decl({ modName: 'type', modVal: 'avatar' }, {
		onSetMod: {
			'js': {
				'inited': function() {
					this.__base.apply(this, arguments);
					console.log('attach_type_avatar inited...');
				}
			}
		},
		_updateFileElem: function() {
			this.__base.apply(this, arguments);
			console.log('_updateFileElem');
			//Do something...
		},
		_clear: function() {
			this.__base.apply(this, arguments);
			console.log('_clear');
			//Do something...
		}
	}));
});
```
Методы срабатывают, 
"Супер-колл" работает,
Функциональность блока не ломается,
только после выбора файла, всплывает ошибка:

Uncaught TypeError: Cannot read property '_emitChange' of undefined
    at Object._onChange (profile_settings.min.js:7695)
    at n.fn.init.<anonymous> (profile_settings.min.js:1643)
    at Function._liveClassTrigger (profile_settings.min.js:1618)
    at HTMLBodyElement.f (jquery.min.js:2)
    at HTMLBodyElement.dispatch (jquery.min.js:3)
    at HTMLBodyElement.r.handle (jquery.min.js:3)

Конкретно в этом месте:
```js
_onChange : function() {
        this.elem('no-file').detach();
        this.getVal()?
            this
                ._updateFileElem()
                ._emitChange() :
            this._clear();
}
```
Как побороть ошибку? Доопределяю кнопки таким же образом - нет никаких ошибок.

**Comment by belozer** [comment]
Какая версия bem-core?

**Comment by belozer** [comment]
для начала не `desktop.blocks/attach/attach.js`
а `desktop.blocks/attach/_type/attach_type_avatar.js`

Но проблема в том, что методы теряют свой контекст. Это точно весь код?

**Comment by sinitsyn-alex** [comment]
@belozer. С путем ошибся, но не суть, в сборку попадает. Да это весь код

**Comment by belozer** [comment]
Хмм.. Хорошо бы ещё узнать версию bem-components и bem-core.

В любом случае попробуй установить дебаггер в `_onChange`  и посмотри на что ссылается `this` и попробуй прямо из дебаггера вызвать методы. Т.к. это странно.

А шаблоны трогал? Если да, хорошо бы шаблон тоже приложить.

**Comment by sinitsyn-alex** [comment]
@belozer. bem-components - 2.5.0, bem-core - 2.9.0. Шаблоны не трогал.
```js
/* attach.bemhtml */
block('attach')(
    def()(function() { return applyNext({ _attach : this.ctx }); }),

    tag()('span'),

    js()(true),

    content()(
        function() {
            var ctx = this.ctx,
                button = ctx.button;

            this.isSimple(button) && (button = {
                block : 'button',
                tag : 'span',
                text : button
            });

            var attachMods = this.mods,
                buttonMods = button.mods || (button.mods = {});
            ['size', 'theme', 'disabled', 'focused'].forEach(function(mod) {
                buttonMods[mod] || (buttonMods[mod] = attachMods[mod]);
            });

            return [
                button,
                {
                    elem : 'no-file',
                    content : this.ctx.noFileText
                }
            ];
        }
    )
);

/* attach.bh.js */
module.exports = function(bh) {

    bh.match('attach', function(ctx, json) {
        ctx
            .tParam('_attach', json)
            .tag('span')
            .js(true);

        var button = json.button;
        typeof button === 'object' || (button = {
            block : 'button',
            tag : 'span',
            text : button
        });

        var attachMods = ctx.mods(),
            buttonMods = button.mods || (button.mods = {});
        ['size', 'theme', 'disabled', 'focused'].forEach(function(mod) {
            buttonMods[mod] || (buttonMods[mod] = attachMods[mod]);
        });

        ctx.content([
            button,
            {
                elem : 'no-file',
                content : json.noFileText
            }
        ], true);
    });


```

**Comment by belozer** [comment]
Останови дебаггер в `_onChange` и посмотри что возвращает `this._updateFileElem()`

**Comment by sinitsyn-alex** [comment]
@belozer. "Дебажнул".
this._updateFileElem() - возвращает undefined.
Поэтому и undefined._emitChange() - выдает ошибку.
This - в _onChange указывает на блок Attach

**Comment by belozer** [comment]
@sinitsyn-alex проверь дебагером ещё здесь https://github.com/bem/bem-components/blob/v2.5.0/common.blocks/attach/attach.js#L90 и здесь https://github.com/bem/bem-core/blob/v2.9.0/common.blocks/i-bem/__dom/i-bem__dom.js#L845

**Comment by sinitsyn-alex** [comment]
@belozer. В обоих случаях ссылка на attach

**Comment by sinitsyn-alex** [comment]
@belozer. Очень странно... В первом обращении там везде ссылка на attach, потом на undefined. Вы сможете повторить мой код у себя на машине?

**Comment by sinitsyn-alex** [comment]
@belozer. Убираю метод _updateFileElem из уже доопределенного атача - ошибка пропадает.
Остальные методы доопределенные не создают ошибок. Как я понял ошибка в библиотеке. Прошу помочь(

**Comment by belozer** [comment]
@sinitsyn-alex я слепой.... У тебя доопределён метод, но возвращаемое значение изменено.
В attach возвращается this, а у тебя изменено на void.

Правильней будет так
```
		_updateFileElem: function() {
                        // Вызов базового метода
			this.__base.apply(this, arguments);
			console.log('_updateFileElem');

                        // возвращаем Attach
                        return this;
		},
```

**Comment by sinitsyn-alex** [comment]
@belozer. Я очень благодарен Вам за решение моей проблемы, спасибо!

**Comment by belozer** [comment]
@sinitsyn-alex всё зависит от того что хочется решить переопределением метода.
this возвращать не обязательно, если его не возвращает базовый метод.

> Хотя вот метод _clear я тоже доопределил и не возвратил this

Возвращать this нужно для работы chain синтаксиса.
https://github.com/bem/bem-components/blob/v2.5.0/common.blocks/attach/attach.js#L64

```
            this
                ._updateFileElem() // возвращаем this
                ._emitChange() : // вызываем метод у возвращённого значения, т.е. this
            this._clear(); // здесь вызов делается напрямую
```

вот что будет при попытке использовать `_clear`
```
this
    ._clear() // после переопределения _clear стал возвращать undefined, вместо this
    ._emitChange(); // ошибка
```

**Comment by sinitsyn-alex** [comment]
@belozer Теперь всё стало на свои места. Спасибо!
