### ISSUE TITLE
Как в React-проекте у DOM-элементов сделать css-классы по origin-схеме

### ISSUE THREAD

**Issue by alexbaumgertner** [bem-site/bem-forum-content-ru#1413]
Подскажите, как в React-проекте у DOM-элементов сделать css-классы вида `<div class=“Button__text_type_submit”>`? 
Пробовал в .bemrc.js — https://github.com/alexbaumgertner/bem-react-example-components/blob/master/.bemrc.js#L7-L24
— не работает.

![button](https://user-images.githubusercontent.com/223620/29793210-bcb7d388-8c4b-11e7-88ab-5da390cb1c5c.png)

Не могу найти, как поменять конфигурацию по умолчанию, судя по коду, это захардкожено:
https://github.com/bem/bem-react-core/blob/master/src/index.js#L10
https://github.com/bem/bem-react-core/blob/master/.bemrc.js#L16

Собирается в 
![brc](https://user-images.githubusercontent.com/223620/29793262-ebaa53aa-8c4b-11e7-952d-f906c8fac10a.png)

Сделал демо https://github.com/alexbaumgertner/bem-react-example-components/pull/1

**Comment by alexbaumgertner** [comment]
Пока решил форком https://github.com/alexbaumgertner/bem-react-core/blob/feature/origin-naming/.bemrc.js#L16

**Comment by belozer** [comment]
@alexbaumgertner а определение `.bemrc` на уровне проекта не помогает? Вроде должно быть достаточно указать его локально.

**Comment by alexbaumgertner** [comment]
@belozer
Пробовал, https://github.com/alexbaumgertner/bem-react-example-components/blob/master/.bemrc.js#L24
не работает.

**Comment by awinogradov** [comment]
@alexbaumgertner ты прав, сейчас берется бэм-конфиг с уровня bem-react-core и твой никак не влияет на нейминг. @tadatuta как нам лучше с этим побороться?

**Comment by awinogradov** [comment]
@alexbaumgertner пока могу предложить у себя на проекте определеить кастомный index.js для bem-react-core:

``` js
// my-project/bem-react-core/index.js
import inherit from 'inherit';
import decls from 'bem-react-core/dist/lib/decls';
import BaseBemReact from 'bem-react-core/dist/lib/BaseComponent';
import simpleComponent from 'bem-react-core/dist/lib/simpleComponent';

const opts = {
    __dangerouslySetNaming : 'origin'
};

export const { decl, declMod } = decls(BaseComponent, {}, opts);

export const {decl, declMod} = decls;
export default SimpleComponent({}, opts);
```

``` js
// my-project/blocks/component/component.js
import { decl } from '../../bem-react-core'

export default decl();
```

Или написать алиас для webpack и тогда будет импорт как и без доопрделения.

**Comment by zxqfox** [comment]
> как нам лучше с этим побороться?

[завести issue в bem-config](https://github.com/bem/bem-sdk/issues/new?labels=pkg:config)

**Comment by tadatuta** [comment]
> как нам лучше с этим побороться?

нужно переставать импортить `.bemrc` и начать, наконец, использовать `bem-config` :)

**Comment by alexbaumgertner** [comment]
Еще вопрос: если я использую нейминг `origin`, то я не могу переопределять bem-react-components, так как [она использует react](https://github.com/bem/bem-react-components/blob/master/.bemrc.js#L7)?
Стили CSS при создании будут Button-Text и на этапе сборки это никак не сконфигурировать?

**Comment by alexbaumgertner** [comment]
@awinogradov спасибо, это лучше чем форк и как временное решение ок.

**Comment by zxqfox** [comment]
Пока bem-react-components не начнет использовать что-то вроде rebem или pobem
И/ИЛИ пока в целом не будет работать побиблиотечная кастомизация нейминга — действительно никак нормальным способом нельзя будет сконфигурировать

**Comment by awinogradov** [comment]
@tadatuta да я бы вообще без проблем, только вот fs чет на клиенте не работает) Даже не знаю как починить)

**Comment by tadatuta** [comment]
@awinogradov мы же все придумали: https://github.com/bem-sdk-archive/bem-config/issues/20#issuecomment-312430632

**Comment by awinogradov** [comment]
Я там понаписал пример того как можно решить без долгих подготовок

**Comment by awinogradov** [comment]
https://github.com/bem/bem-react-core/issues/133
