### ISSUE TITLE
Принудительная сброска кэша у пользователей сайта в браузере

### ISSUE THREAD

**Issue by sinitsyn-alex** [bem-site/bem-forum-content-ru#1414]
Появилась необходимость принудительно сбрасывать кэш css, js бандлов на страницах.
Смотрел в сторону добавления версий по типу: index.css?v=2   или   index.css?v= new Date()
Как лучше всего реализовать "версионность" бандлов для project-stub?
В make.js? Или есть готовый инструмент-модуль для бэм-а в целом?
Было бы не плохо увидеть пример этой реализации.

**Comment by tadatuta** [comment]
`borschik` умеет генерировать хеш-суммы от контента файлов, это идеальный вариант — кэш будет жить до тех пор, пока в файле реально не произойдут изменения. См. https://github.com/borschik/borschik/blob/master/docs/freeze/freeze.ru.md

**Comment by sinitsyn-alex** [comment]
@tadatuta спасибо за ответ. К сожалению, я не нашел примера для моей задачи.
И еще, все css и js указаны в bemjson бандла. Каким образом они автоматически будут обновляться на хеш-сумму файла? Борщик - это умеет?

**Comment by sinitsyn-alex** [comment]
@tadatuta Help. borschik прекрасно умеет заменять ссылки в css.
А мне необходимо заменить ссылки в bemjson.js бандла.
Нашел ваше решение для замены ссылок в конечном html: https://ru.bem.info/forum/646/#comment-149028367
Но оно не подходит, так как мне не нужен конечный html для backend. а нужен bemjson
