### ISSUE TITLE
bem-express и разные бандлы

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1430]
Добрый день.

Не понимаю как реализовать несколько бандлов, например, по всем запросам должен генерироваться бандл `index`, в блоке `root` подключаются файлы `index.min.css`, `index.min.js` и другие - это понятно. Как сделать несколько страниц тоже понятно.
Далее, хотел сделать админку, запрос `/admin`, но у нее свои стили и скрипты и вот тут непонятно уже как их подключить, ведь используется все тот же блок `root`. 
И логично было бы чтобы все нужные файлы собирались в `desktop.bundles/admin`

Расскажите подробнее про это.

**Comment by godfreyd** [comment]
Привет.

Измени немного шаблон `common.blocks/root/root.bemtree.js`:

```js
block('root').replace()(function() {

var data = this.data = this.ctx.data,
        page = data.page,
        siteBundle = page.bundle;  // Получаем bundle

// какой-то код. Полностью не пишу

styles: [
      {
            elem: 'css',
            url: data.root + '/' + siteBundle + '.min.css'
       }
],
scripts: [
     {
           elem: 'js',
           url: data.root + '/' + siteBundle + '.min.js'
     }
 ],

// какой-то код
});
```

И опиши маршрутизацию для `/admin` в файле  `server/index.js`

```
app.get('/admin', function(req, res) {
    render(req, res, {
        title: 'Admin page',
        meta: {
            description: 'Page description',
            og: {
                url: 'https://site.com/admin',
                siteName: 'Site name'
            }
        }
    })
});
```

**Comment by Realetive** [comment]
@Kundin и вот тут ещё пример — https://github.com/Realetive/bem-express-ext

**Comment by Kundin** [comment]
Огромное спасибо за пример!
Теперь стало понятно и попутно нашел ответ на свою след проблему, а именно разделение на desktop и touch и функцию isCallerMobile
