### ISSUE TITLE
События на lazy-сущностях

### ISSUE THREAD

**Issue by lilliputten** [bem-site/bem-forum-content-ru#1432]
Немного запутался, подскажите, пож.: задача реагировать на события "ленивого" блока.

Делаю примерно так:
```javascript
var lazyBlock = this.findChildBlock(SomeLazyBlock);
this._events(lazyBlock).on('someEvent', this.onSomeEvent);
```
Но во время `findChildBlock` оно уже автоматически инициализируется, так?

Существует ли способ сохранить неинициализированное состояние и при этом реагировать на события?

**Comment by belozer** [comment]
@lilliputten вроде так должно быть, если мне память не изменяет :)

`this._events(SomeLazyBlock).on('someEvent', this.onSomeEvent, this);`

**Comment by skad0** [comment]
В данном случае ты подписываешься на события ленивого блока из какого-то другого. 
Почему бы тебе не подписываться на него из lazy секции? Тогда достаточно будет подписываться не на экземпляр, а на сам класс.

```javascript
bemDom.declBlock('myBlock', {
 onSetMod: { 
    // ... 
 }
}, {
  lazyInit: true,

  onInit: function() {
    this._events(SomeLazyBlock).on('event', this.prototype._onSomeEvent);
  }
});
```

**Comment by skad0** [comment]
> Существует ли способ сохранить неинициализированное состояние и при этом реагировать на события?

А с этим вот непонятно. Ведь реагировать на событие = проинициализироваться и что-то сделать же.

**Comment by lilliputten** [comment]
@skad0 Нет, вроде как раз так и получается. Во время экспериментов вроде бы было отмечено именно такое поведение: до первого события блок остаётся неинициализированным.

**Comment by skad0** [comment]
>@skad0 Нет, вроде как раз так и получается. Во время экспериментов вроде бы было отмечено именно такое поведение: до первого события блок остаётся неинициализированным.

Так и должно быть. Тогда не понял в чем проблема) 
Если хочешь чтобы блоки себя так вели подписывайся как я указал выше.
