### ISSUE TITLE
Митап по БЭМ для новичков. Москва, 15 декабря

### ISSUE THREAD

**Issue by innabelaya** [bem-site/bem-forum-content-ru#1437]
**UPD** Опубликовали видео доклада про bem-react-core: 
https://youtu.be/2pKg-xGg1gI?t=38

**Ты должен прийти, если:**
- только начинаешь верстать или знакомится с БЭМ;
- верстаешь давно, но хочешь перейти на сторону, где есть печеньки;
- используешь БЭМ только для CSS и уже готов двигаться дальше;
- хочешь узнать, как получить все плюсы БЭМ-проекта.

В программе: 
- доклад от @tadatuta 
- секция вопросов/ответов с @veged, @tadatuta и @vithar
- рассказ о bem-react-core от @awinogradov

Регистрация уже открыта: https://events.yandex.ru/events/bemup/15-december-2017/

**Stay BEMed!**

**Comment by bemdev** [comment]
Приветствую) а будет запись где нибудь?

**Comment by innabelaya** [comment]
@bemdev Добрый день! Сегодня опубликуем.

**Comment by bemdev** [comment]
круто, мне понравилось очень, еще бы все части детектива.
