### ISSUE TITLE
Есть ли какие-нибудь средства, которые проверяют - насколько моя верстка (CSS и HTML) соответствует БЭМ'у?

### ISSUE THREAD

**Issue by ulin-evgeny** [bem-site/bem-forum-content-ru#1441]
Здравствуйте! Я изучаю БЭМ. Хочу взять от него CSS и HTML (то есть, только методологию наименований). Есть ли средства, которые могут проанализировать мою верстку и стили и показать, насколько она соотвествует БЭМ? 
Я вот сверстаю макет. А как понять - правильно ли (с точки зрения БЭМ) я его сверстал (написал HTML и CSS. Без раскладывания элементов по папкам). Может, я как-то не так понял эту методолгию. Но если нет возможности проверить работу на правильность, как я об этом узнаю?

**Comment by godfreyd** [comment]
Привет. Автоматизированных средств проверки нет и скорее всего не может быть. Слишком большая вариативность того, что можно проверять. Единственно верным решением будет следовать всем рекомендациям методологии. После 2-3 сверстанных макетов, никакой инструмент тебе не понадобится. Можешь ориентироваться на сайт bem.info и параллельно сверяться с методологией.

**Comment by Realetive** [comment]
Ну почему же? Можно, например, проверить структуру вложенности элементов и соблюдение конвенции именования с помощью https://github.com/shakyShane/bem-validator и https://github.com/awinogradov/postcss-bem-validator
