### ISSUE TITLE
Баг в документации?

### ISSUE THREAD

**Issue by ishpagin** [bem-site/bem-forum-content-ru#1471]
Добрый день. Кто скажет, это так задумано выводить такое юзеру, или это баг?

например тут:
https://ru.bem.info/methodology/css/#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B

я вижу:
![1](https://pp.userapi.com/c830709/v830709779/56137/ISB-W56sCYk.jpg)
![2](https://pp.userapi.com/c830709/v830709779/56140/wq2V0j5hXqo.jpg)

вместо "человеческого" html и css. Очень сложно разбирать примеры из-за лишних тегов и символов.

Google Chrome Версия 64.0.3282.119 (Официальная сборка), (64 бит)

**Comment by innabelaya** [comment]
@ishpartko Добрый день! Задачу уже завели: https://github.com/bem-site/bem.info/issues/253

**Comment by ishpagin** [comment]
@innabelaya спасибо за ответ, тогда ждем
