### ISSUE TITLE
API bemhtml/bemtree

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1486]
Два вопроса:
1. Очень интересует где я могу включить доп. опции для шаблонов, такие как закрытие одиночных элементов, аттрибуты без кавычек - читал тут https://ru.bem.info/platform/bem-xjst/8/api/
Использую bem express и я должен это делать в файле `.enb/techs.js`, (?) так как шаблоны подключаются там
```js
module.exports = {
    bemtree: require('enb-bemxjst/techs/bemtree'),
    bemhtml: require('enb-bemxjst/techs/bemhtml')
}
```
Можно какой-то элементарный пример?

2. Как убрать стандартную обработку текста, например, мне иногда важно чтобы сохранялись переносы строк в тексте.

**Comment by Realetive** [comment]
1. Почти. Конфиг задаётся уже в сборщике, т. е. в случае с `bem-express` — в `.enb/make.js`:

```javascript
// .enb/make.js (xjst/bemhtml@)
// …
  node.addTechs([
    // …
    [techs.bemhtml, {
      sourceSuffixes: ['bemhtml', 'bemhtml.js'],
      forceBaseTemplates: true,
      engineOptions: {
        elemJsInstances: true,
        xhtml: false,
        omitOptionalEndTags: true,
        unquotedAttrs: true,
        runtimeLint: true
      },
    }],
    // …
  ]);
// …
```
2. https://ru.bem.info/platform/bem-xjst/8/api/#%D0%AD%D0%BA%D1%80%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
P. S. вместо изменения лучше использовать специальную директиву (как описано в доке по ссылке):

```javascript
{
  content: {
    html: 'Не&shy;раз&shy;рыв&shy;ный&nbsp;про&shy;бел'
  }
}
```

**Comment by Kundin** [comment]
@Realetive 
1. Все работает.
2. Как раз использовал свойство `html`, но переносы строк все равно съедались, сейчас решил проблему совершенно случайно - добавив `white-space: pre-line;` тексту. 
Спасибо за помощь.
