### ISSUE TITLE
Модификаторы с одним названием но разными значениями у одной сущности

### ISSUE THREAD

**Issue by vill** [bem-site/bem-forum-content-ru#1493]
Всем привет. Допустимо чтобы одна сущность имела несколько модификаторов с одним названием но разными значениями? Если да, то можете привести корректные примеры таких модификаторов?

Такое допустимо:
```html
<div class="block block_theme_sun block_theme_green-islands"></div>
```

```html
<div class="block block_size_m block_size_l"></div>
```

или у сущности название модификатора должно встречаться только один раз, например если есть модификатор `block_size_m` тогда сущность больше не может иметь модификаторов у которых название `size` то есть `block_size_l` нельзя использовать.

**Comment by tadatuta** [comment]
Может быть только одно значение определенного модификатора, т.е. верно второе утверждение:

> если есть модификатор block_size_m тогда сущность больше не может иметь модификаторов у которых название size то есть block_size_l нельзя использовать

**Comment by vill** [comment]
Понятно, спасибо.
