### ISSUE TITLE
bemtree/bemhtml to html

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1502]
Научите собирать из ```bemtree``` шаблонов ```html``` автоматически, т.к. у меня не используется bemjson-файла и использовать ```bemjson-to-html``` не могу. А как ещё собрать готовый ```html``` понять не могу. Пример конфигурации enb можно посмотреть в этом [проекте](https://github.com/Kundin/taxi-alex), по сути там всё стандартно, ничего не менялось с образца BemExpress.
Но html должен собираться для каждой папки  ```pages/*```, так как каждый бандл у меня это общий шаблон-обвязка (например общий шаблон публичной части сайта и общий шаблон панели администратора), а вот каждая папка в ```pages``` это шаблон именно уникальной страницы (например шаблон страницы статьи, который вставлен в шаблон публичной части сайта). Соответственно на выходе сборки было бы неплохо иметь что-то вроде ```bundles/desktop.bundles/название-страницы.html```.
Вот.

**Comment by Realetive** [comment]
@Kundin 

https://github.com/bem/bem-express/blob/master/server/render.js#L64

```
fs.writeFile("/path/to/destination.html", html, function(err) {
    if ( err ) {
        return console.log( err );
    }
    console.log("The file was saved!");
}); 
```

**Comment by Realetive** [comment]
Соответсвенно,
`"/path/to/destination.html"`
можно заменить на
`path.join( pathToBundle, bundleName + '.html' )`.

**Comment by Kundin** [comment]
@Realetive Спасибо, почему-то совсем не думал о такой реализации, единственный минус это чтобы собрать/обновить html сразу всех страниц нужно дополнительно написать поиск их всех по проекту или зайти на каждую возможную. Но это несложно, будем пользоваться =) 
Думаю логичным будет этот скрипт вообще вынести в npm scripts и тогда удобно, красиво.
