### ISSUE TITLE
Ошибки при генерации проекта через yo bem-stub

### ISSUE THREAD

**Issue by web-jade** [bem-site/bem-forum-content-ru#1507]
Ни как не могу понять, почему у меня постоянно лезут ошибки и не дают сгенерировать проект.

web-jade@webjade-Aspire-TC-120:~/Documents/bemes$ yo bem-stub
? Enter your project name: bem-test
? Enter a name of the project owner: Nikita
? Enter an email of the project owner: web-kostrov@yandex.ru
? Choose a toolkit to build the project: ENB
? Specify additional libraries if needed: 
? Choose redefinition levels to use: desktop
? Choose CSS preprocessor: Only pure CSS
? Do you want to use 'Autoprefixer'? No
? Choose technologies to be used in the project: BEMJSON, BEMTREE, browser.js
? Choose a template engine: BEMHTML
? Do you want to build static HTML? Yes
? Do you want to build 'tidy' HTML? No
? Choose types of files to be minimized: css, js
   create bem-test/.bowerrc
   create bem-test/.enb/make.js
   create bem-test/bower.json
   create bem-test/desktop.bundles/index/index.bemjson.js
   create bem-test/.gitignore
   create bem-test/package.json
   create bem-test/README.md

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN deprecated enb-diverse-js@0.1.0: Use `enb-js` instead.
npm WARN deprecated bem-xjst@1.2.1: v1.x is deprecated. Use v4.x or newer. See https://github.com/bem/bem-xjst/wiki/Migration-guides
npm WARN deprecated coa@1.0.3: Please upgrade to 1.0.4 for node 0.10, 0.12, or to 2.0+ for node 4+
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> bem-test@0.0.0 postinstall /home/web-jade/Documents/bemes/bem-test
> npm run deps

> bem-test@0.0.0 deps /home/web-jade/Documents/bemes/bem-test
> bower install

bower bem-core#v2.8.0           cached https://github.com/bem/bem-core.git#2.8.0
bower bem-core#v2.8.0         validate 2.8.0 against https://github.com/bem/bem-core.git#v2.8.0
bower bem-core#v2.8.0          install bem-core#2.8.0

bem-core#2.8.0 libs/bem-core
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN borschik-tech-cleancss@2.1.0 requires a peer of borschik@>=1.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN enb-modules@0.2.0 requires a peer of ym@~0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN vow-node@0.3.0 requires a peer of vow@0.4.x but none is installed. You must install peer dependencies yourself.

added 295 packages from 273 contributors and audited 1111 packages in 19.615s
found 41 vulnerabilities (25 low, 11 moderate, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
✔ Done!

**Comment by web-jade** [comment]
web-jade@webjade-Aspire-TC-120:~/Documents/bemes$ yo bem-stub
? Enter your project name: bem-test
? Enter a name of the project owner: Nikita
? Enter an email of the project owner: web-kostrov@yandex.ru
? Choose a toolkit to build the project: ENB
? Specify additional libraries if needed: 
? Choose redefinition levels to use: desktop
? Choose CSS preprocessor: Only pure CSS
? Do you want to use 'Autoprefixer'? No
? Choose technologies to be used in the project: BEMJSON, BEMTREE, browser.js
? Choose a template engine: BEMHTML
? Do you want to build static HTML? Yes
? Do you want to build 'tidy' HTML? No
? Choose types of files to be minimized: css, js
   create bem-test/.bowerrc
   create bem-test/.enb/make.js
   create bem-test/bower.json
   create bem-test/desktop.bundles/index/index.bemjson.js
   create bem-test/.gitignore
   create bem-test/package.json
   create bem-test/README.md

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN deprecated enb-diverse-js@0.1.0: Use `enb-js` instead.
npm WARN deprecated bem-xjst@1.2.1: v1.x is deprecated. Use v4.x or newer. See https://github.com/bem/bem-xjst/wiki/Migration-guides
npm WARN deprecated coa@1.0.3: Please upgrade to 1.0.4 for node 0.10, 0.12, or to 2.0+ for node 4+
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> bem-test@0.0.0 postinstall /home/web-jade/Documents/bemes/bem-test
> npm run deps


> bem-test@0.0.0 deps /home/web-jade/Documents/bemes/bem-test
> bower install

bower bem-core#v2.8.0           cached https://github.com/bem/bem-core.git#2.8.0
bower bem-core#v2.8.0         validate 2.8.0 against https://github.com/bem/bem-core.git#v2.8.0
bower bem-core#v2.8.0          install bem-core#2.8.0

bem-core#2.8.0 libs/bem-core
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN borschik-tech-cleancss@2.1.0 requires a peer of borschik@>=1.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN enb-modules@0.2.0 requires a peer of ym@~0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN vow-node@0.3.0 requires a peer of vow@0.4.x but none is installed. You must install peer dependencies yourself.

added 295 packages from 273 contributors and audited 1111 packages in 19.615s
found 41 vulnerabilities (25 low, 11 moderate, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
✔ Done!

**Comment by web-jade** [comment]
web-jade@webjade-Aspire-TC-120:~/Documents/bemes$ yo bem-stub
? Enter your project name: bem-test
? Enter a name of the project owner: Nikita
? Enter an email of the project owner: web-kostrov@yandex.ru
? Choose a toolkit to build the project: ENB
? Specify additional libraries if needed: 
? Choose redefinition levels to use: desktop
? Choose CSS preprocessor: Only pure CSS
? Do you want to use 'Autoprefixer'? No
? Choose technologies to be used in the project: BEMJSON, BEMTREE, browser.js
? Choose a template engine: BEMHTML
? Do you want to build static HTML? Yes
? Do you want to build 'tidy' HTML? No
? Choose types of files to be minimized: css, js
   create bem-test/.bowerrc
   create bem-test/.enb/make.js
   create bem-test/bower.json
   create bem-test/desktop.bundles/index/index.bemjson.js
   create bem-test/.gitignore
   create bem-test/package.json
   create bem-test/README.md

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN deprecated enb-diverse-js@0.1.0: Use `enb-js` instead.
npm WARN deprecated bem-xjst@1.2.1: v1.x is deprecated. Use v4.x or newer. See https://github.com/bem/bem-xjst/wiki/Migration-guides
npm WARN deprecated coa@1.0.3: Please upgrade to 1.0.4 for node 0.10, 0.12, or to 2.0+ for node 4+
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> bem-test@0.0.0 postinstall /home/web-jade/Documents/bemes/bem-test
> npm run deps


> bem-test@0.0.0 deps /home/web-jade/Documents/bemes/bem-test
> bower install

bower bem-core#v2.8.0           cached https://github.com/bem/bem-core.git#2.8.0
bower bem-core#v2.8.0         validate 2.8.0 against https://github.com/bem/bem-core.git#v2.8.0
bower bem-core#v2.8.0          install bem-core#2.8.0

bem-core#2.8.0 libs/bem-core
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN borschik-tech-cleancss@2.1.0 requires a peer of borschik@>=1.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN enb-modules@0.2.0 requires a peer of ym@~0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN vow-node@0.3.0 requires a peer of vow@0.4.x but none is installed. You must install peer dependencies yourself.

added 295 packages from 273 contributors and audited 1111 packages in 19.615s
found 41 vulnerabilities (25 low, 11 moderate, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
✔ Done!

**Comment by web-jade** [comment]
Ошибки тут 
https://pastebin.com/Sz6SybnM

**Comment by Realetive** [comment]
Ответ в самом репозитории: https://github.com/bem-archive/generator-bem-stub/commit/d483acc71af814b5f47fbe48e05be6b0a2ceee9e
