### ISSUE TITLE
Помогите советом с инитом блока select

### ISSUE THREAD

**Issue by bemdev** [bem-site/bem-forum-content-ru#1514]
@tadatuta Доброе время суток!

Не пойму в связи с чем получаю такую штуку 

Uncaught Error: declMod with lazyInit prop not allowed. Your need use 'lazyInit' in data-bem params

Когда прикрепляют select блок 

код блока
`{ 
            block: 'select', 
            mods: { mode: 'radio', theme: 'islands', size: 'xl' },
            name: 'auto',
            val: 1,
            options: [
                { val: '1', text: 'BMW' }
            ]
        },`

код зависимостей 

`({
    shouldDeps: [
        { elems: [ 'title' ] },
        { block: 'input', mods: { theme: 'islands', 'has-clear': true, type: 'text', size: 'xl' } },
        { block: 'textarea', mods: { theme: 'islands', size: 'xl' } },
        { block: 'button', mods: { theme: 'islands', size: 'xl' } },
        { block: 'select', mods: { mode: 'radio', theme: 'islands', size: 'xl' } },
    ]
})`

в чем же тут дело?

**Comment by Realetive** [comment]
Ловил такую проблему на новом bem-core. В чём дело не знаю, но помогло откатиться на предыдущую версию 4.2.1.

**Comment by bemdev** [comment]
@Realetive Спасибо, сменил версию все заработало. Думал, дело во мне :D

**Comment by tadatuta** [comment]
Мы выпустили минор bem-core v4.3.1, где откатили это дело, так что можно наоборот обновиться.
