### ISSUE TITLE
Видео по BEMTREE

### ISSUE THREAD

**Issue by safinayrat** [bem-site/bem-forum-content-ru#1515]
Добрый день) Подскажите дальнейший путь развития. Я понял саму методологию, научился верстать через bemjson, а дальше что...Если это шаблоны(BEMHTML,BEMTREE) то есть ли видео где более подробно про это рассказано?

**Comment by bemdev** [comment]
Приветы!

Конечно есть, вот пример https://www.youtube.com/watch?v=4D90HexDyOY
Рассказывают, что все не только про css
