### ISSUE TITLE
Как не терять modal окно?

### ISSUE THREAD

**Issue by bemdev** [bem-site/bem-forum-content-ru#1516]
Добрый вечер @tadatuta !

Помогите понять как правильно написать.

```
{
    elem: 'link',
    tag: 'li',
    content: [
        link.title,
        {
            block: 'modal',
            mods: { theme: 'islands', autoclosable: true },
            content: [
                {
                    block: 'card',
                    dataContent: {
                        title: link.title,
                        image: link.image,
                        text: link.text,
                        text_title: link.text_title,
                        check_list: link.check_list
                    }
                }
            ]
        },
    ]
}

```

Хотел открыть модал блок по клику на элемент линк и показать какой то карточный контент, но модал блок попадает куда то в корень. Как мне его потом ловить? Или как правильно обновить контент блок примерно в этой логике?

**Comment by tadatuta** [comment]
См. в качестве примера https://github.com/tadatuta/bem-bricks/tree/master/common.blocks/info-modal

**Comment by bemdev** [comment]
У меня есть немного глупый наверно вопрос, но я смотрю разные проекты на бэм и часто хватает только bemhtml шаблона, когда Вы применяете bemtree, что бы разделить логику данные и html? Или писать сразу в одном и желательно тогда сразу в bemhtml обычно выполняет все нужны?

**Comment by kompolom** [comment]
@bemdev Мы используем bemtree чтобы преобразовать данные в bemjson а потом bemhtml чтобы из bemjson сделать html.

**Comment by bemdev** [comment]
@kompolom в моем понимании почему то сложилось, что все что про 'content' это в bemtree. Это совсем ошибочное понимание?

**Comment by tadatuta** [comment]
@bemdev чаще всего так и получается, да )
