### ISSUE TITLE
"Дети-модификаторы"?

### ISSUE THREAD

**Issue by ghost** [bem-site/bem-forum-content-ru#1517]
```
<h1 class="heading-primary">
    <span class="heading-primary--main">Outdoors</span>
    <span class="heading-primary--sub">is where life happens</span>
</h1>
```

```
.heading-primary {
    color: #ffffff;
    text-transform: uppercase;
}

.heading-primary--main {
    font-size: 6rem;
}

.heading-primary--sub {
    font-size: 2rem;
}
```

Это - пример разметки и оформления блока-заголовка. Источник - англоязычный курс Advanced CSS and Sass авторства _Jonas Schmedtmann_.  
Ссылка на репозиторий: https://github.com/jonasschmedtmann/advanced-css-course/blob/master/Natours/final-after-S06/index.html  
**Вопрос** - этот пример использования модификаторов не противоречит общепринятым рекомендациям по БЭМ-наименованию селекторов? Возможно ли использование модификаторов в отрыве от модифицируемого блока\элемента при условии, аналогичном или близком по своей сути к коду выше?

**Comment by Realetive** [comment]
@nick-everhard,
1) да, https://ru.bem.info/methodology/naming-convention/
2) нет, это не имеет смысла, т. к. точно не возможно определить принадлежность модификатора

**Comment by yialo** [comment]
На мой взгляд, span'ы в примере должны быть элементами блока .heading-primary – например, 

> .heading-primary__main

 и 

> .heading-primary__sub,

т.к. они не могут использоваться без родителя .heading-primary.

Также они могут быть элементами одного типа – например,

> .heading-primary__string,

но с разными модификаторами – например,

> .heading-primary__string--main

и

> .header-primary__string--sub.
