### ISSUE TITLE
Контентная область страницы

### ISSUE THREAD

**Issue by mikhin** [bem-site/bem-forum-content-ru#1520]
Как правильно подговить верстку по БЭМу для использования на сайте, где контент-менеджер не использует классы для элементов (например, контент-менеджер публикует новости в блоге на сайте компании)?

Пример: я готовлю стили для блока .content и его потомков: .content h1, .content h2, .content h3, .content p, .content img. В таком случае элементы других блоков, внутри блока .content, переопределяются стилями для потомков .content, т.к. специфичность класса .content p - выше. Как правильно поступить?

**Comment by Realetive** [comment]
Используйте классы для всех сущностей, до которых у вас есть доступ, а для области «вмешательства» менеджера используйте специфичность CSS через теги:

```
.content
  .content__header
  .content__manager
  .content__footer
```

```
.content__manager a {}
.content__manager img {}
.content__manager p {}
```
