### ISSUE TITLE
Как реализовать наследование от распространенных элементов?

### ISSUE THREAD

**Issue by brachkow** [bem-site/bem-forum-content-ru#1524]
Допустим у нас есть класс `.link` который задает стили для всех ссылок на странице, есть элемент `.navbar__link` который должен унаследовать стили от класса `.link`.

Как это правильно реализовать?

P.S. Тут написно как нужно: https://ru.bem.info/methodology/css/#Стилизация-групп-блоков

**Comment by belozer** [comment]
Можно через html
```
// navbar/__link/navbar__link.deps.js
[{ mustDeps : ['link'] }]

// navbar/__link/navbar__link.bemhtml.js
block('navbar').elem('link).addMix({ block : 'link' });
```

А можно через extend в stytus (или другом процессоре).
