### ISSUE TITLE
Использование миксов

### ISSUE THREAD

**Issue by brachkow** [bem-site/bem-forum-content-ru#1526]
Есть микс для параграфа `.paragraph`. Он используется для параграфов в различных элементах, в том числе для элементов-параграфов в блоке `.article`. Однако в этом блоке необходимо добваить еще стили для параграфа.

Как я понимаю это будет реализовыватся как то так (с добавлением элемента `.article__paragraph`):

```
<div class="article">
  <div class="article__paragraph paragraph"></div>
</div>

```

Это явлется правильным?

**Comment by Realetive** [comment]
Да.
