### ISSUE TITLE
Почему потерялся ModBody? @bem-react/core )

### ISSUE THREAD

**Issue by bemdev** [bem-site/bem-forum-content-ru#1551]
Приветствую, балуюсь с новой библиотекой и видимо, что то с руками)

```
import * as React from 'react';
import { withBemMod, ModBody } from '@bem-react/core';
import { IButtonProps } from '../index';

const ButtonLink: ModBody<IButtonProps> = (Base, { text, className }) => (

  // className === 'Button Button_type_link'

  <a className={className}>{text}</a>
);

export const ButtonTypeLink = withBemMod<IButtonProps>('Button', { type: 'link' }, ButtonLink);
```

библиотеки обновил, но не понимаю почему там нет ModBody, ведь я так хочу менять не только стили )

и еще момент я так понимаю className основного блока должен сам приехать. Или я не прав?

Помогите пожалуйста советом, добрые люди.

**Comment by lilliputten** [comment]
Присоединяюсь. Попробовал обновиться на последний `@bem-react/core`, поглядел, потом откатился на последнюю "рабочую" `^1.2.0`.

Полагаю, мантайнеры опять меняют (в процессе или уже поменяли) концепцию, но обновить документацию руки не доходят. В общем, пока выжидаем.

**Comment by bemdev** [comment]
Все так и есть, метод называется как то Enhance теперь и видимо немного по другому работает. Лучше смотреть тогда исходники и пытаться понять как оно там работает) и было б чудом получить новую документацию с таким же примером.
