### ISSUE TITLE
Как разметить структурно сложный но при этом нереюзабельный элемент?

### ISSUE THREAD

**Issue by brachkow** [bem-site/bem-forum-content-ru#1560]
Как правильно размечать структурно сложные, но одноразовые элементы: бем-блоком или бем-элементом родителя?

**Comment by Realetive** [comment]
Элементом.

**Comment by brachkow** [comment]
В таком случае что делать если появляется вот такая структура:

```
<div class="block">
  <div class="block__item"></div>
  <div class="block__item"></div>
  <div class="block__item"></div>
  <ul class="block__list">
    <li class="block__list-item"></li>
    <li class="block__list-item"></li>
    <li class="block__list-item"></li>
  </ul>
</div>
```

?

Элемент list не реиспользуемый. Но название block__list-item уже «привязывает» блок к списку, те напрашивается создание блока.
