### ISSUE TITLE
Допустим ли каскад в модификаторах?

### ISSUE THREAD

**Issue by brachkow** [bem-site/bem-forum-content-ru#1562]
Можно ли перезаписывать стили дочерних элементов через каскад от модификатора?

Например вот так:

```
.block {
  &__content {
    background-color: red;
  }
 
  &__text {
    display: block;
  }
 
  &_active {
    .block__content {
      background-color: blue;
    }
    
    .block__text {
      display: flex;
    }
  }
}
```

**Comment by Realetive** [comment]
@brachkoff да. Так, например, часто поступают при стилизации по модификатору темы, если вместо CSS Custom propetries используется каскад.
