### ISSUE TITLE
Использование псевдоклассов в БЕМ

### ISSUE THREAD

**Issue by brachkow** [bem-site/bem-forum-content-ru#1565]
В верстке я часто использую псевдоклассы `:first-child`, `:last-child`, `:nth-child` и тд. Они позволяют избежать ошибок при изменении верстки.

Допустимо ли **повсеместное** использование таких псевдоклассов в БЭМ? Или стоит использовать их только в крайней необходимости, в остальных случая заменяя модификаторами?

**Comment by Realetive** [comment]
В Яндексе, на сколько я знаю, причина использования модификаторов появилась из необходимости тестировать определённые состояния, которые выражаются псевдоклассами, так что, если в этом необходимости нет, то **повсеместное** — вполне допустимо.
