### ISSUE TITLE
Допустимо ли изменение блока через каскад от микса?

### ISSUE THREAD

**Issue by brachkow** [bem-site/bem-forum-content-ru#1575]
Допустим у меня есть блок `.article`:

```
<div class="article">
  <h1 class="article__heading"></h1>
  <img class="artilce__image">
  <p class="article__text"></p>
</div>
```

Я хочу видоизменить его внутри блока `.frontpage`, при этом сохранив привязку к `.article`. Для этого я использую микс только к `.article`:

```
.frontpage{
  &__article{
    .article{
      &__heading{}
      &__image{}
      &__text{}
    }
  }
}
```

Такой подход (в отличии от миксования к каждому изменному блоку) позволяет мне не засорять пространство имен (никаких  ` .frontpage__article-heading`), и вроде бы не ломает модульность.

Соответствует ли он методологии?

**Comment by Realetive** [comment]
Тот же визуальный эффект можно получить с помощью модификатора, но без увеличения специфичности:

```
.article_view_frontpage {
  &__heading{}
  &__image{}
  &__text{}
}
```

Это более правильная БЭМ-практика.

**Comment by Realetive** [comment]
При этом [внешняя геометрия](https://ru.bem.info/methodology/css/#%D0%B2%D0%BD%D0%B5%D1%88%D0%BD%D1%8F%D1%8F-%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F-%D0%B8-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) для `.article` будет описана в `.frontpage__article`.
