### ISSUE TITLE
Могу ли я использовать файловую структуру БЭМ по сути только для scss файлов ?

### ISSUE THREAD

**Issue by sergei-kh** [bem-site/bem-forum-content-ru#1578]
Здравствуйте, подскажите пожалуйста, я создаю проект на framework laravel и хочу использовать файловую структуру БЭМ для моих стилей (scss), соответственно в html разметке у меня блоки и элементы именованы по правилам как в документации.
**Вопрос в том что считается ли такая ситуация правильной когда у меня допустим в папке для элемента находиться только один файл ?** Потому что js файлы, мне всё таки удобнее было бы хранить в другом месте, не разбивать их как стили.  
К примеру:
```
/header
   __logo
      header__logo.scss
   __menu
   __search
```
Получается что у меня вот в папке __logo будет только один файл. Да и вообще во многих папка может быть только один файл. К примеру если я захочу добавить модификатор какой то к logo  
получится такое:
```
/header
   __logo
      _center
         _header__logo_center.scss
      header__logo.scss
   __menu
   __search
```
В папке _center один файл только.
Заранее благодарю за ответ.

**Comment by Realetive** [comment]
@sergeyWebstyle да, абсолютно нормально. Расширение файла означает технологию, в которой описывается БЭМ-сущность (блок или элемент), а если её достаточно, ну что же, ничего страшного (потом может добавиться ещё — отдельные стили для другой темы, тесты, документация).

**Comment by sergei-kh** [comment]
@Realetive понял, благодарю
