### ISSUE TITLE
Форма на БЭМ

### ISSUE THREAD

**Issue by imballama** [bem-site/bem-forum-content-ru#1581]
Доброго времени суток. Правильная ли форма с точки зрения БЭМ? Больше всего вопросов вызвало присваивание классов элементам fieldset и label

```
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="merged/merge.min.css"/>
</head>
<body>
    <div class="header">
        <span class="logo">
            <img src="" alt="" />
        </span>
    </div>
    <div class="main">
        <form class="auth-form" enctype="application/x-www-form-urlencoded" method="post">
            <fieldset class="auth-form__fieldset">
                <label class="auth-form__label">Логин</label>
                <input type="text" class="auth-form__input_text"/>
            </fieldset>
        </form>
    </div>
</body>
</html>
```

**Comment by certainlyakey** [comment]
Да, с точки зрения БЭМ все выглядит правильно. Классы БЭМ-элементов одного блока можно присваивать на различных уровнях вложенности DOM, если вас это смущает.

Другое дело, что есть проблема с использованием fieldset — он используется для группировки нескольких полей, часто одинакового типа, а не для группировки лейбла и инпута. Плюс у label отсутствует атрибут for.

**Comment by Realetive** [comment]
Если используется BEMJSON, то советую посмотреть реализацию в [bem-forms](https://github.com/bem-contrib/bem-forms), там достаточно удобная архитектура + валидация + поддержка разных типов полей.
