### ISSUE TITLE
Мой первый написаный код по БЭМ

### ISSUE THREAD

**Issue by ghost** [bem-site/bem-forum-content-ru#1583]
Можете сказать правильно я сделал или нет ? 
``<html>

    <head>
        <link rel="stylesheet" href="style.css">
        <link rel="stylesheet" href="media.css">
        <meta name="keywords" content="Жизнь,работа,новости">
        <meta name="description" content="MyLife - Это прекрасная жизнь, чтобы иди дальше....">
        <title> Сайт </title>
    </head>
    <body>    
      <header>
        <div class="container">
            <div class="menu">
                <div class="block-logo">
                    <img class="block-logo__image"src="Image/Logo.png">
                </div>
                <div class="block-button">
                    <a class="block-button__text" href="#">work</a>
                    <a class="block-button__text" href="#">news</a>
                    <a class="block-button__text" href="#">about me</a>
                </div>
            </div>
            <h1 class="name">Slice of my life.</h1>
            <div class="block-schroll">
                <img class="block-schroll__img" src="Image/Mouse.png">
                <p class="block-schroll__text">Schroll to see more</p>
            </div>
        </div>
    </header>        
    </body>
</html>``

**Comment by Realetive** [comment]
Явных ошибок именования нет, но для полного ответа нужно чётко понимать, какую задачу должен был решить БЭМ.

**Comment by ghost** [comment]
Здравствуйте, можно чуток пожалуйста по подробней ) . Да, я понимаю что вы мне можете не отвечать, но просто хочется сразу выяснить какие ошибки есть, а каких нет. И как понимать " Какую задачу должен был решить БЭМ " Вроде все объявлял в классы. 
С уважением Евгений.

**Comment by Realetive** [comment]
> какие ошибки есть, а каких нет

— Чтобы ответить на этот вопрос, нужно знать, где вы их могли допустить. Перечислять возможные ошибки бессмысленно, а написать «классы через чёрточку» — много ума не надо. Если задача была «написать какой-то абстрактный пример HTML-разметки и упомянуть в классах именование по БЭМ», то тут это более-менее есть (правда, непонятно, кому и зачем это было нужно — примеров в интернетах полно).

> [Какую задачу должен был решить БЭМ](https://ru.bem.info/methodology/solved-problems/)

**Comment by ghost** [comment]
Спасибо большое за ваш ответ. Я просто только начал обучаться, как я уже
говорил. И хочу обучаться более правильно, а не просто так.

пт, 5 июля 2019 г. в 22:11, Realetive <notifications@github.com>:

**Comment by vitaly44** [comment]
Мне явно не нравится 

```
<div class="block-button">
    <a class="block-button__text" href="#">work</a>
    <a class="block-button__text" href="#">news</a>
    <a class="block-button__text" href="#">about me</a>
</div>

```

блок с кнопками, а внутри ссылки… странно это, внутри должны быть кнопки, а не ссылки, если это навигация по странице — тогда это на блок с кнопками, а nav-button.

Далее **__text** это ведь не текст, а элемент блока, типа __item тогда уж.

Я как-то так это вижу.
