### ISSUE TITLE
класс для заголовка

### ISSUE THREAD

**Issue by lonecatkz** [bem-site/bem-forum-content-ru#1585]
Здравствуйте!
Такой вопрос.
Например создаем секцию с классом intro:  
< section class="intro"> 
Как правильно задать класс заголовка в этой секции: 

1) < h1 class="intro_title">

2)< h1 class="intro intro_title">

3) < h1 class="title">

**Comment by sh4rov** [comment]
Приветствую! Если у меня на странице много секций, где заголовок будет одинаковый (или почти), то я просто пишу отдельный базовый класс типа** ```.title-section ```** а далее что коснется отдельных стилей для заголовка определенной секции, то я пишу стили в **```.intro__title```** т.е. это выглядит примерно так: 
```
<section class="block-one">
  <h1 class="section-title block-one__title">
    В мире животных
  </h1>
</section>

<section class="block-two">
  <h1 class="section-title block-two__title">
    В мире животных 2!
  </h1>
</section>
```

В БЭМ это называется Микс, если я не ошибаюсь :)

**Comment by lonecatkz** [comment]
БОЛЬШОЕ спасибо за ответ! Теперь понятно.

**Comment by get-web** [comment]
> В БЭМ это называется Микс, если я не ошибаюсь :)

Тогда уже так:

```
section-title block-one__section-title
```
