### ISSUE TITLE
Автоматическая генерация папок

### ISSUE THREAD

**Issue by AkanoCA** [bem-site/bem-forum-content-ru#1594]
Добрый день, друзья! 
Никак не могу разобраться.. 
Подскажите пожалуйста, есть ли возможность автоматической генерации структуры папок и css файлов на основе написания их в чистом html? 

Т.е. например, я пишу: 

```
<div class="search search_theme_sand"> 
```

И автоматически, или по нажатию "волшебной" кнопки у меня генерируется структура: 

```
common.bloks 
  search 
    _theme_sand
    search_theme_sand.css
  search.css
```

Нашел вроде как bemgo, но что-то у меня ничего не работает

**Comment by Realetive** [comment]
https://github.com/bem-site/bem-forum-content-ru/issues/1591

**Comment by AkanoCA** [comment]
Разобрался, благодарю.. 
Ни сразу дошло, что нужно проект в папку app с bemgo помещать.. 
Долго очень мучился с этим)

**Comment by AkanoCA** [comment]
Нет, не разобрался, поместил свой проект, а структура не генерируется
