### ISSUE TITLE
BEMGO

### ISSUE THREAD

**Issue by AkanoCA** [bem-site/bem-forum-content-ru#1595]
Доброго времени суток.
Подскажите, пожалуйста, если есть знающие люди, как подключать изображения в bemgo?

**Comment by Realetive** [comment]
Думаю, ответ будет быстрее получен на ресурсах, посвящённых bemgo (а лучше обратиться к документации).

**Comment by AkanoCA** [comment]
Обращался к документации
Обращался к демо-версии сайта заложенной в папке с проектом
Просматривал код

Но что-то явно упускаю
