### ISSUE TITLE
Подскажите, правильно написана разметка

### ISSUE THREAD

**Issue by mikhaylenko** [bem-site/bem-forum-content-ru#1601]
Есть такая разметка

```
<section class="section section-icon section-icon--image--paper">
  <div class="container">
    <div class="section-icon__left">
      <h2 class="section__heading">Heading 2</h2>
      <img src="/img/paper.svg" alt="" />
      <p>Text section</p>
    </div>
  </div>
</section>
```

Интересует правильно ли используется подход БЭМ?
Может ли содержать класс ` section-icon--image--paper` модификатор и его значение, что изменяет внешний вид секции в целом? 

```

```

**Comment by manwithawp** [comment]
Может ли содержать класс section-icon--image--paper модификатор и его значение, что изменяет внешний вид секции в целом? - ДА
