### ISSUE TITLE
Плагин для сборки БЭМ проектов на gulp

### ISSUE THREAD

**Issue by al-korzh** [bem-site/bem-forum-content-ru#1607]
Будьте добры, подскажите какой плагин стоит использовать для gulp, чтоб собирать БЭМ проекты? Желательно с документацией, тк новичок во всем этом :)

**Comment by hvab** [comment]
Использую
`gulp-bem-bundle-builder`
`gulp-bem-bundler-fs`

Вот пример https://github.com/hvab/palecore/blob/master/gulpfile.js
