### ISSUE TITLE
Добрый день! Нужен совет для новичка

### ISSUE THREAD

**Issue by SantaRiver** [bem-site/bem-forum-content-ru#1628]
Решил начать изучать bem пользуясь enb. Попутно хочу научится применять sass. Пользовался в осномном [этой](https://ru.bem.info/tutorials/classic/start-with-project-stub/) статьей. Там они, к слову не создавали элементы, но писали стили элементов блоков прям в стилях блоках. И вот что получилось:
Создаю блок и элемент к нему, даю им по scss:

```
bem create -l desktop.blocks -b some-block -T scss
bem create -l desktop.blocks -b some-block -m some-elem -T scss
```
Далее говорю sass следить за все делом в папке desktop.blocks что бы тот формировал css
```
sass --watch desktop.blocks/ 
```
И далее идет некоторая магия enb (я еще не добрался до этого, в документации немного неясно описывается принцип сборки бандлов) и формируется наш готовый бандл
```
desktop.bundles/index/index.css
```
Собственно вопрос. Делают ли так вообще? Sass бы заиграл более ярко, если бы я писал все стили елементов в блоках. Например:
```
.some-block {
   &__some-elem {
      /* Стили элемента */
   }
}
```
Но тогда зачем нужно отдельно создавать элементы? Заранее спасибо

**Comment by b1tc0re** [comment]
Если я правильно понял вопрос то попробую объяснить.

Допустим у нас есть блок button у него есть элемент  **button__loading** которые рисует иконку загрузки. 
Если на странице у вас не будет кнопок с загрузкой стили и скрипты элемента button__loading не попадут в конечные файлы project.js и procjet.css
