### ISSUE TITLE
Управление select с клавиатуры в 2.1

### ISSUE THREAD

**Issue by resure** [bem-site/bem-forum-content-ru#353]
Кажется, в 2.1.0 поломалось управление с клавиатуры (вроде перехода между элементами в попапе стрелками и выбора пробелом).

Пример:
- [2.0](https://ru.bem.info/__example/bem-components/v2.0.0/desktop.examples/select/38tbBjnCJNexcB1xBlVHQNMLy04/38tbBjnCJNexcB1xBlVHQNMLy04.html)
- [2.1](https://ru.bem.info/__example/bem-components/v2.1.0/desktop.examples/select/38tbBjnCJNexcB1xBlVHQNMLy04/38tbBjnCJNexcB1xBlVHQNMLy04.html)

**Comment by tadatuta** [comment]
@resure Спасибо, завел https://github.com/bem/bem-components/issues/1456
