### ISSUE TITLE
Про rem unit и клонирование темы

### ISSUE THREAD

**Issue by immuzov** [bem-site/bem-forum-content-ru#662]
## 1. Rem единицы

Ребят, а почему вы не используете rem единицы? Из-за поддержки ie8? Есть же плагины которые сами считают и проставляют для варианта:
- в rem
- в px

Что-то подобное:

``` css
.input {
  padding: 1rem .5rem;
  padding: 16px 8px; /* Дописывает плагин при сборке */
}
```

Так сложилось или есть подводные камни?
## 2. Клонирование темы islands

Я понял что у вас тема – это stylesheet представление блоков (design/*.blocks), а вся остальная логика обозначена в *.blocks. Форкнул тему, переименовал, добавляю в нее свои блоки, меняю стили и дописываю блоки темы islands. Про форк темы прочитал [здесь](https://github.com/bem/bem-forum-content-ru/issues/592).

Вопросы:
1. Сильно ли я пострадаю от того что замораживаюсь на текущей версии темы? Часто ли происходят глобальные изменения темы? Меняю форматирование в файлах стилей, диффы отследить сложно. Боюсь за то что (например) блок select обновится, а у меня что нибудь да отвалится.
2. Стоит ли в теме менять px -> rem?

@tadatuta привет! :-)

**Comment by tadatuta** [comment]
1. `rem` не используется скорее по историческим причинам — не было нужды. Поддержка IE8 у нас опциональная (код вынесен в отдельные файлы), так что при наличии реальных доводов в пользу `rem`, их вполне можно было бы использовать.

2. Про тему не уверен, что правильно понял вопрос, но идея в том, чтобы продолжать использовать актуальную версию `bem-components`, но в сборку проекта вместо уровней `bem-components/design/*.blocks` подключить свой собственный уровень с реализацией собственной темы.

Изменения в файлах темы время от времени случаются. В частности прямо сейчас висят пулл-реквесты на небольшие изменение дизайна. Но если новая тема принципиально отличается от темы `islands`, то по-идее такие обновления не должны быть важны в любом случае.

**Comment by Immuzov** [comment]
2. Да, все верно, использовать свою, но пока она отличается от islands незначительно, например, цвета, паддинги. Задел на будущее так сказать.

@tadatuta Спасибо вам!

**Comment by JiLiZART** [comment]
@Immuzov
в своем проекте подключил postcss с px to rem плагином, который во всех местах где встречается `line-height` и `font-size` в пикселях так же добавляет дублирующие свойства с `rem` что обеспечивает поддержку старых браузеров и включает `rem` в новых

**Comment by Immuzov** [comment]
@JiLiZART А это только для line-height и font-size?

**Comment by JiLiZART** [comment]
@Immuzov https://github.com/cuth/postcss-pxtorem

**Comment by Immuzov** [comment]
@JiLiZART Спасибо!
