### ISSUE TITLE
БЭМ и meteor

### ISSUE THREAD

**Issue by JWo1F** [bem-site/bem-forum-content-ru#691]
Вечер добрый! Подскажите пожалуйста, какие есть инструменты для работы с БЭМ, используя метеор? :)

**Comment by tadatuta** [comment]
Я ничего специального не встречал, но т.к. инструменты написаны на JS, то вполне будут работать и в связке с `meteor`.

**Comment by JWo1F** [comment]
Хотелось бы чего-то более автоматизированного. Жаль, спасибо!

**Comment by tadatuta** [comment]
@JWo1F Какие именно задачи хочется решать с помощью инструментов?
