### ISSUE TITLE
BEM + React

### ISSUE THREAD

**Issue by alexbaumgertner** [bem-site/bem-forum-content-ru#746]
UPD: можно попробовать https://github.com/bem/create-bem-react-app

Привет!
Хочется попробовать сделать React-компоненты с использованием методологии BEM: разделение на блок-элемент-модификатор и на уровни
common, desktop, touch.
Нашел пока вот:
- https://github.com/yummies/starter-kit – слишком молодо и много зависимостей
- https://github.com/artemshitov/react-bem – скорее всего сильно устарело
- [Реактивные интерфейсы с React.js и БЭМ: мастер класс. Слава Аристов](https://github.com/aristov/react-tutorial) – интересно, смотрю
- https://github.com/dfilatov/bem-react – заморожено, но интересно, смотрю

Порекомендуйте пожалуйста еще источников.

**Comment by zxqfox** [comment]
У тебя два раза dfilatov/bem-react

**Comment by blond** [comment]
Ещё есть такое https://github.com/Yeti-or/bem-hazard, но, наверное не то.

**Comment by jchouse** [comment]
Я вот так сделал: https://github.com/jchouse/reactjs-starter-kit

**Comment by JiLiZART** [comment]
https://github.com/yummies/yummies

**Comment by alexbaumgertner** [comment]
@JiLiZART слишком молодо и много зависимостей (папка `node_modules` 90Mb). Боюсь, в текущем проекте у нас не хватит времени до ума доводить.

**Comment by alexbaumgertner** [comment]
@blond интересно, но слишком абстрактно. Как идея пригодится, спасибо!

**Comment by ihorzenich** [comment]
@alexbaumgertner на чём в итоге остановился? Как насчёт вот этого форка https://github.com/dfilatov/bem-react -> https://github.com/react-bem/react-bem ?

**Comment by Guria** [comment]
Самое актуальное почему-то никто не упомянул:
#961
awinogradov/react-bl

**Comment by Guria** [comment]
А yummies вроде теперь https://github.com/rebem

**Comment by alexbaumgertner** [comment]
@ihorzenich
@Guria

Спасибо ребята за информацию, пока ни на чем не остановился.

Попробую поэкспериментировать в https://github.com/alexbaumgertner/presentation-bem-spa

**Comment by awinogradov** [comment]
@alexbaumgertner а чем не подошло https://github.com/awinogradov/react-bl ?

**Comment by alexbaumgertner** [comment]
@awinogradov
пока не пробовал — на момент написания топика еще не было  https://github.com/awinogradov/react-bl.

**Comment by awinogradov** [comment]
@alexbaumgertner теперь все в твоих руках ;)

**Comment by kot-lex** [comment]
https://github.com/rebem выглядит заманчиво. 
Кто-нибудь кроме авторов использует это в продакшене?

**Comment by awinogradov** [comment]
Чем именно он тебя манит?:) там только классы и схожесть с форматом bemjson :(

**Comment by JiLiZART** [comment]
Там готовая экосистема, есть лоадер для вебпака реализующий уровни,
трансформер для jsx, тузлы для тестов, даже для postcss плагин написали

вт, 24 мая 2016 г. в 11:53, Anton Winogradov <notifications@github.com>:

**Comment by awinogradov** [comment]
Тогда чего ты хочешь от БЭМ в React? Все что ты перечислил все про React, кроме postCSS, пожалуй. Там нет шаблонов, а кажется уровни вот прям про них и про браузерный JS.

**Comment by vithar** [comment]
Мы используем postcss плагин.

**Comment by alexbaumgertner** [comment]
Наконец-то можно попробовать: https://github.com/bem/create-bem-react-app
