### ISSUE TITLE
YENV

### ISSUE THREAD

**Issue by vkhv** [bem-site/bem-forum-content-ru#872]
Всем привет, хотелось бы подробнее узнать о переменной YENV, есть какая-нибудь дополнительная информация, ссылки? :)

**Comment by tadatuta** [comment]
@campykid ссылок, к сожалению, нет, но эта переменная часто используется в модулях сборки для получения сборки в production-режиме (`YENV=production`).

**Comment by ilyar** [comment]
Дополнительные ссылки можно найти любимым поисковиком по запросу: `YENV site:ru.bem.info`.
