### ISSUE TITLE
Rails и БЭМ

### ISSUE THREAD

**Issue by navff** [bem-site/bem-forum-content-ru#919]
Добрый день!
Мне предстоит подружить БЭМ и Ruby on Rails. Проблема видится так: разработка фронтенда на полном БЭМ-стеке — это отдельный процесс, никак не связанный с разработкой на рельсах. БЭМ-разработчик верстает красивую страничку, а потом её нужно каким-то образом перенести в .erb или в .haml. Каждый раз при изменениях на фронтенде процесс проноса в rails будет вызывать дикую боль.

Нашёл на эту тему один пост на местном форуме (https://ru.bem.info/forum/-389/) и  два поста на Хабре:
https://habrahabr.ru/post/192972/  (2013 год)
https://habrahabr.ru/post/229121/  (2014 год)

У обоих авторов есть проекты на гитхабе, но обновляются эти проекты не часто.
https://github.com/gkopylov/bem
https://github.com/awinogradov/bem-on-rails

Думается, что со времени написания этих двух статей кое-что изменилось и в БЭМе и в рельсах. Вопрос в зал: кто и что знает о дружбе Rails и БЭМ? Что изменилось? Есть ли новые проекты? Мастер-классы?

Было бы очень интересно увидеть рабочий пример с использованием bem-components и родным рельсовым сборщиком.

**Comment by awinogradov** [comment]
@navff привет! Кажется самый безболезненный способ это использовать Rails как API. А клиент поднять на nodejs. Но скорее всего ты скажешь, что затея неочень, а зря) Другой вариант это заиспользовать V8 для рендера шаблоново внутри Ruby. Все очень сильно зависит от того чего хочется. Если хочешь просто писать по БЭМу с блоками и шаблонизаторами мира Rails, то https://github.com/awinogradov/bem-on-rails хватит. Если хочешь все библиотеки компонентов, написанные на bemhtml, скажем, то тут возможны варианты, описанные выше. Рассказывай подробно чего хочешь сделать.

**Comment by navff** [comment]
@awinogradov Благодарю. Из предложенных вариантов подошёл бы «просто писать по БЭМу с блоками и шаблонизаторами мира Rails», но я не очень понимаю, как это совместить с bem-components. Где должны оказаться компоненты и их кастомные темы в файловой структуре? 

По bem-on-rails было бы очень здорово поиметь пример.В идеале, с bem-components. У вас почти такой пример был, но сейчас пропал с гитхаба. Может, выложите свежий?

**Comment by awinogradov** [comment]
Ответ очень простой: никак. Как бы грустно это не было.
