### ISSUE TITLE
js код, обработчики событий на форму

### ISSUE THREAD

**Issue by Leo19909** [bem-site/bem-forum-content-ru#944]
Помоги пожалуйста .js ява скриптом, а именно с функцией <select id="mySelect" onchange="myFunction()">документ во вложении, но не могу никак настроить, и гугл не помогает, css файлы есть, html во вложении, форма поиска показывается на сайте замечательно, но вот не выбирает ни город не категорию - вернее выбирает но ссылку на кнопке НАЙТИ не выбирает ту которая относится к выбранному городу и категории. Поисковик с сайта my-svadba.ru над слайдером. Буду очень благодарен, неделю мучаюсь( При попытке выбрать город или  категорию не меняется ссылка предназначенная данному городу и категории - <a id="choose_city_link" class="btn" href="/auth/reset_city/?return=/all/category/all">

[search.js.txt](https://github.com/bem/bem-forum-content-ru/files/191790/search.js.txt)
[search.htmI.txt](https://github.com/bem/bem-forum-content-ru/files/191791/search.htmI.txt)

**Comment by Leo19909** [comment]
вот сам htm код 
<div class="search-for-performer">
	
		
	<h1 class="search-for-performer__header">Найдите идеального исполнителя</h1>
	<h2>Более 49 856 свадебных фирм в 257 городах </h2>

	<form class="look-for">
	  	<div class="select-container">
				<select name="choose_city" id="choose_city" onchange="city_change(this);"><option value="all">Город</option><option value="not"> Город не выбран!</option><option value="abakan">Абакан</option><option value="Napa">Айя-Напа</option><option value="alma-ata">Алма-Ата</option><option value="almetevsk">Альметьевск</option><option value="anapa">Анапа</option><option value="armavir">Армавир</option><option value="arhangelsk">Архангельск</option><option value="astrahan">Астрахань</option><option value="baku">Баку</option><option value="balakovo">Балаково</option><option value="baranovichi">Барановичи</option><option value="barnaul">Барнаул</option><option value="barcelona">Барселона</option><option value="belgorod">Белгород</option><option value="berlin">Берлин</option><option value="biysk">Бийск</option><option value="blagoveschensk">Благовещенск</option><option value="bobruysk">Бобруйск</option><option value="bratsk">Братск</option><option value="bryansk">Брянск</option><option value="budapesht">Будапешт</option><option value="bourgas">Бургас (Болгария)</option><option value="velikieluki">Великие Луки</option></select>
		<span class="select-container__icon">▼</span>
    </div>


    	<div class="select-container">
		
<select id="choose_category" name="choose_category" title="Категория" style=""><option value="">Услуга</option><optgroup id="159" label="Без раздела"><option value="160">Раздел каталога не выбран!</option></optgroup><optgroup id="56" label="Видео и Фото"><option value="2">Видеографы</option><option value="3">Фотографы</option><option value="14">Фотопечать и фотокниги</option></optgroup><optgroup id="161" label="Для свадебного стола"><option value="12">Торты</option><option value="42">Кейтеринг</option><option value="43">Напитки для застолья</option></optgroup><optgroup id="40" label="Место для банкета"><option value="6">Рестораны, кафе, бары</option><option value="142">Базы отдыха и Усадьбы</option></optgroup><optgroup id="108" label="Молодоженам"><option value="20">Выставки</option><option value="23">Порталы и сайты</option><option value="26">Журналы</option><option value="30">ЗАГСЫ</option><option value="33">Обустройство дома</option><option value="107">Разные специалисты</option></optgroup><optgroup id="34" label="Наряды и украшения"><option value="7">Свадебные и вечерние платья</option></optgroup></select>
	<span class="select-container__icon">▼</span>
    </div>

    <a id="choose_city_link" class="btn" href="/auth/reset_city/?return=/all/category/all">
      Найти
    </a>
  </form>

</div>

вот js 

 /*  $TOGGLE SEARCH FORM INTO HEADER
   ------------------------------------ */
  var timerId = null,
      $searchForm = $('.search-form');

  $("#search").hover(
      function () {
        clearTimeout(timerId);
        $searchForm.show();
        $(this).parent().addClass('hovered');
      },
      function () {
        var $this = $(this);
        timerId = setTimeout(function () {
          $searchForm.hide();
          $this.parent().removeClass('hovered');
        }, 300);

        $searchForm.bind('mouseenter', function () {
          clearTimeout(timerId);
        });
        $searchForm.bind('mouseleave', function () {
          $("#search").parent().removeClass('hovered');
          $(this).hide();
        })
      }
  );


При выборе города или категории не меняется сама ссылка, стоит на месте будто выбора и не было <a id="choose_city_link" class="btn" href="/auth/reset_city/?return=/all/category/all">

**Comment by Leo19909** [comment]
не знаю как сюда закачать файлы напишу так вот html
`<div class="search-for-performer">
	
		
	<h1 class="search-for-performer__header">Найдите идеального исполнителя</h1>
	<h2>Более 49 856 свадебных фирм в 257 городах </h2>

	<form class="look-for">
	  	<div class="select-container">
				<select name="choose_city" id="choose_city" onchange="city_change(this);"><option value="all">Город</option><option value="not"> Город не выбран!</option><option value="abakan">Абакан</option><option value="Napa">Айя-Напа</option><option value="alma-ata">Алма-Ата</option><option value="almetevsk">Альметьевск</option><option value="anapa">Анапа</option><option value="armavir">Армавир</option><option value="arhangelsk">Архангельск</option><option value="astrahan">Астрахань</option><option value="baku">Баку</option><option value="balakovo">Балаково</option><option value="baranovichi">Барановичи</option><option value="barnaul">Барнаул</option><option value="barcelona">Барселона</option><option value="belgorod">Белгород</option><option value="berlin">Берлин</option><option value="biysk">Бийск</option><option value="blagoveschensk">Благовещенск</option><option value="bobruysk">Бобруйск</option><option value="bratsk">Братск</option><option value="bryansk">Брянск</option><option value="budapesht">Будапешт</option><option value="bourgas">Бургас (Болгария)</option><option value="velikieluki">Великие Луки</option></select>
		<span class="select-container__icon">Ў</span>
    </div>


    	<div class="select-container">
		
<select id="choose_category" name="choose_category" title="Категория" style=""><option value="">Услуга</option><optgroup id="159" label="Без раздела"><option value="160">Раздел каталога не выбран!</option></optgroup><optgroup id="56" label="Видео и Фото"><option value="2">Видеографы</option><option value="3">Фотографы</option><option value="14">Фотопечать и фотокниги</option></optgroup><optgroup id="161" label="Для свадебного стола"><option value="12">Торты</option><option value="42">Кейтеринг</option><option value="43">Напитки для застолья</option></optgroup><optgroup id="40" label="Место для банкета"><option value="6">Рестораны, кафе, бары</option><option value="142">Базы отдыха и Усадьбы</option></optgroup><optgroup id="108" label="Молодоженам"><option value="20">Выставки</option><option value="23">Порталы и сайты</option><option value="26">Журналы</option><option value="30">ЗАГСЫ</option><option value="33">Обустройство дома</option><option value="107">Разные специалисты</option></optgroup><optgroup id="34" label="Наряды и украшения"><option value="7">Свадебные и вечерние платья</option></optgroup></select>
	<span class="select-container__icon">Ў</span>
    </div>

    <a id="choose_city_link" class="btn" href="/auth/reset_city/?return=/all/category/all">
      Найти
    </a>
  </form>

</div>`

**Comment by kompolom** [comment]
А где собственно, у вас код который должен менять ссылку?

**Comment by Leo19909** [comment]
да, вот не знаю( Этот поисковик я подсмотрел на сайте моя-свадьба.ру тот что поверх слайдера,  мне такой же нужен но только стили css то есть внешний вид будет свой, а вот реализовать на своем сайте никак не могу. Писал в интернете и  обработчики событий и куски кода брал и вписывал, везде только про выпадающий список а про кнопку и взаимодействие ноль инфы...

**Comment by Leo19909** [comment]
Ребят помогите с этим поисковиком очень нужно..
